DROP SEQUENCE AD_Error_Seq;

CREATE SEQUENCE AD_Error_Seq START WITH 1 INCREMENT BY 1;

DROP SEQUENCE AD_PInstance_Seq;

CREATE SEQUENCE AD_PInstance_Seq START WITH 1 INCREMENT BY 1;

DROP SEQUENCE T_Spool_Seq;

CREATE SEQUENCE T_Spool_Seq START WITH 1 INCREMENT BY 1;

DROP SEQUENCE W_BASKET_SEQ;

CREATE SEQUENCE W_BASKET_SEQ START WITH 1 INCREMENT BY 1;

