--
-- ad_menu
-- 

INSERT INTO ad_process (ad_process_id, 
                                  ad_client_id, 
                                  ad_org_id, 
                                  isactive, 
                                  created, 
                                  createdby, 
                                  updated, 
                                  updatedby, 
                                  value, 
                                  name, 
                                  description, 
                                  help, 
                                  accesslevel, 
                                  entitytype, 
                                  procedurename, 
                                  isreport, 
                                  isdirectprint, 
                                  ad_reportview_id, 
                                  classname, 
                                  statistic_count, 
                                  statistic_seconds, 
                                  ad_printformat_id, 
                                  workflowvalue, 
                                  ad_workflow_id, 
                                  isbetafunctionality, 
                                  isserverprocess, 
                                  showhelp, 
                                  jasperreport)
                                  VALUES 
                                 (53002, 
                                  0, 
                                  0, 
                                  'Y', 
                                  TO_TIMESTAMP('2007-11-3 21:38:36:0','YYYY-MM-DD HH:MI:SS:MS'), 
                                  0, 
                                  TO_TIMESTAMP('2007-11-3 21:38:36:0','YYYY-MM-DD HH:MI:SS:MS'), 
                                  0, 
                                  'Setup Web POS', 
                                  'Setup Web POS', 
                                  NULL, 
                                  NULL, 
                                  '3', 
                                  'C', 
                                  NULL, 
                                  'N', 
                                  'N', 
                                  NULL, 
                                  'org.posterita.process.SetupWebPOS', 
                                  0, 
                                  0, 
                                  NULL, 
                                  NULL, 
                                  NULL, 
                                  'N', 
                                  'N', 
                                  'Y', 
                                  NULL);

INSERT INTO ad_menu (ad_menu_id, 
                               ad_client_id, 
                               ad_org_id, 
                               isactive, 
                               created, 
                               createdby, 
                               updated, 
                               name, 
                               updatedby, 
                               description, 
                               issummary, 
                               issotrx, 
                               isreadonly, 
                               action, 
                               ad_window_id, 
                               ad_workflow_id, 
                               ad_task_id, 
                               ad_process_id, 
                               ad_form_id, 
                               ad_workbench_id, 
                               entitytype)
                               VALUES 
                              (53013, 
                               0, 
                               0, 
                               'Y', 
                               TO_TIMESTAMP('2007-11-3 21:38:38:0','YYYY-MM-DD HH:MI:SS:MS'), 
                               0, 
                               TO_TIMESTAMP('2007-11-3 21:38:38:0','YYYY-MM-DD HH:MI:SS:MS'), 
                               'Setup Web POS', 
                               0, 
                               NULL, 
                               'N', 
                               'N', 
                               'N', 
                               'P', 
                               NULL, 
                               NULL, 
                               NULL, 
                               53002, 
                               NULL, 
                               NULL, 
                               'C');



--
-- ad_process_access
-- 

UPDATE ad_process_access SET created = TO_TIMESTAMP('2007-11-3 21:16:37:125','YYYY-MM-DD HH:MI:SS:MS'), 
                                       updated = TO_TIMESTAMP('2007-11-3 21:16:37:125','YYYY-MM-DD HH:MI:SS:MS') WHERE ad_process_id = 52003 AND ad_role_id = 0;
UPDATE ad_process_access SET created = TO_TIMESTAMP('2007-11-3 21:16:37:125','YYYY-MM-DD HH:MI:SS:MS'), 
                                       updated = TO_TIMESTAMP('2007-11-3 21:16:37:125','YYYY-MM-DD HH:MI:SS:MS') WHERE ad_process_id = 52003 AND ad_role_id = 102;
UPDATE ad_process_access SET created = TO_TIMESTAMP('2007-11-3 21:16:37:125','YYYY-MM-DD HH:MI:SS:MS'), 
                                       updated = TO_TIMESTAMP('2007-11-3 21:16:37:125','YYYY-MM-DD HH:MI:SS:MS') WHERE ad_process_id = 52003 AND ad_role_id = 103;


--
-- ad_process_para
-- 

INSERT INTO ad_process_para (ad_process_para_id, 
                                       ad_client_id, 
                                       ad_org_id, 
                                       isactive, 
                                       created, 
                                       createdby, 
                                       updated, 
                                       updatedby, 
                                       name, 
                                       description, 
                                       help, 
                                       ad_process_id, 
                                       seqno, 
                                       ad_reference_id, 
                                       ad_reference_value_id, 
                                       ad_val_rule_id, 
                                       columnname, 
                                       iscentrallymaintained, 
                                       fieldlength, 
                                       ismandatory, 
                                       isrange, 
                                       defaultvalue, 
                                       defaultvalue2, 
                                       vformat, 
                                       valuemin, 
                                       valuemax, 
                                       ad_element_id, 
                                       entitytype)
                                       VALUES 
                                      (53012, 
                                       0, 
                                       0, 
                                       'Y', 
                                       TO_TIMESTAMP('2007-11-3 21:38:37:0','YYYY-MM-DD HH:MI:SS:MS'), 
                                       0, 
                                       TO_TIMESTAMP('2007-11-3 21:38:37:0','YYYY-MM-DD HH:MI:SS:MS'), 
                                       0, 
                                       'Price List Version', 
                                       'Identifies a unique instance of a Price List', 
                                       'Each Price List can have multiple versions.  The most common use is to indicate the dates that a Price List is valid for.', 
                                       53002, 
                                       20, 
                                       19, 
                                       NULL, 
                                       NULL, 
                                       'M_PriceList_Version_ID', 
                                       'Y', 
                                       10, 
                                       'Y', 
                                       'N', 
                                       NULL, 
                                       NULL, 
                                       NULL, 
                                       NULL, 
                                       NULL, 
                                       450, 
                                       'C');
INSERT INTO ad_process_para (ad_process_para_id, 
                                       ad_client_id, 
                                       ad_org_id, 
                                       isactive, 
                                       created, 
                                       createdby, 
                                       updated, 
                                       updatedby, 
                                       name, 
                                       description, 
                                       help, 
                                       ad_process_id, 
                                       seqno, 
                                       ad_reference_id, 
                                       ad_reference_value_id, 
                                       ad_val_rule_id, 
                                       columnname, 
                                       iscentrallymaintained, 
                                       fieldlength, 
                                       ismandatory, 
                                       isrange, 
                                       defaultvalue, 
                                       defaultvalue2, 
                                       vformat, 
                                       valuemin, 
                                       valuemax, 
                                       ad_element_id, 
                                       entitytype)
                                       VALUES 
                                      (53013, 
                                       0, 
                                       0, 
                                       'Y', 
                                       TO_TIMESTAMP('2007-11-3 21:38:37:0','YYYY-MM-DD HH:MI:SS:MS'), 
                                       0, 
                                       TO_TIMESTAMP('2007-11-3 21:38:37:0','YYYY-MM-DD HH:MI:SS:MS'), 
                                       0, 
                                       'Organization', 
                                       'Organizational entity within client', 
                                       'An organization is a unit of your client or legal entity - examples are store, department. You can share data between organizations.', 
                                       53002, 
                                       10, 
                                       19, 
                                       NULL, 
                                       130, 
                                       'AD_Org_ID', 
                                       'Y', 
                                       10, 
                                       'Y', 
                                       'N', 
                                       NULL, 
                                       NULL, 
                                       NULL, 
                                       NULL, 
                                       NULL, 
                                       113, 
                                       'C');
INSERT INTO ad_process_para (ad_process_para_id, 
                                       ad_client_id, 
                                       ad_org_id, 
                                       isactive, 
                                       created, 
                                       createdby, 
                                       updated, 
                                       updatedby, 
                                       name, 
                                       description, 
                                       help, 
                                       ad_process_id, 
                                       seqno, 
                                       ad_reference_id, 
                                       ad_reference_value_id, 
                                       ad_val_rule_id, 
                                       columnname, 
                                       iscentrallymaintained, 
                                       fieldlength, 
                                       ismandatory, 
                                       isrange, 
                                       defaultvalue, 
                                       defaultvalue2, 
                                       vformat, 
                                       valuemin, 
                                       valuemax, 
                                       ad_element_id, 
                                       entitytype)
                                       VALUES 
                                      (53014, 
                                       0, 
                                       0, 
                                       'Y', 
                                       TO_TIMESTAMP('2007-11-3 21:38:37:0','YYYY-MM-DD HH:MI:SS:MS'), 
                                       0, 
                                       TO_TIMESTAMP('2007-11-3 21:38:37:0','YYYY-MM-DD HH:MI:SS:MS'), 
                                       0, 
                                       'Bank', 
                                       'Bank', 
                                       'The Bank is a unique identifier of a Bank for this Organization or for a Business Partner with whom this Organization transacts.', 
                                       53002, 
                                       50, 
                                       19, 
                                       NULL, 
                                       NULL, 
                                       'C_Bank_ID', 
                                       'Y', 
                                       10, 
                                       'Y', 
                                       'N', 
                                       NULL, 
                                       NULL, 
                                       NULL, 
                                       NULL, 
                                       NULL, 
                                       835, 
                                       'C');
INSERT INTO ad_process_para (ad_process_para_id, 
                                       ad_client_id, 
                                       ad_org_id, 
                                       isactive, 
                                       created, 
                                       createdby, 
                                       updated, 
                                       updatedby, 
                                       name, 
                                       description, 
                                       help, 
                                       ad_process_id, 
                                       seqno, 
                                       ad_reference_id, 
                                       ad_reference_value_id, 
                                       ad_val_rule_id, 
                                       columnname, 
                                       iscentrallymaintained, 
                                       fieldlength, 
                                       ismandatory, 
                                       isrange, 
                                       defaultvalue, 
                                       defaultvalue2, 
                                       vformat, 
                                       valuemin, 
                                       valuemax, 
                                       ad_element_id, 
                                       entitytype)
                                       VALUES 
                                      (53015, 
                                       0, 
                                       0, 
                                       'Y', 
                                       TO_TIMESTAMP('2007-11-3 21:38:37:0','YYYY-MM-DD HH:MI:SS:MS'), 
                                       0, 
                                       TO_TIMESTAMP('2007-11-3 21:38:37:0','YYYY-MM-DD HH:MI:SS:MS'), 
                                       0, 
                                       'Bank Account', 
                                       'Account at the Bank', 
                                       'The Bank Account identifies an account at this Bank.', 
                                       53002, 
                                       60, 
                                       19, 
                                       NULL, 
                                       NULL, 
                                       'C_BankAccount_ID', 
                                       'Y', 
                                       10, 
                                       'Y', 
                                       'N', 
                                       NULL, 
                                       NULL, 
                                       NULL, 
                                       NULL, 
                                       NULL, 
                                       836, 
                                       'C');
INSERT INTO ad_process_para (ad_process_para_id, 
                                       ad_client_id, 
                                       ad_org_id, 
                                       isactive, 
                                       created, 
                                       createdby, 
                                       updated, 
                                       updatedby, 
                                       name, 
                                       description, 
                                       help, 
                                       ad_process_id, 
                                       seqno, 
                                       ad_reference_id, 
                                       ad_reference_value_id, 
                                       ad_val_rule_id, 
                                       columnname, 
                                       iscentrallymaintained, 
                                       fieldlength, 
                                       ismandatory, 
                                       isrange, 
                                       defaultvalue, 
                                       defaultvalue2, 
                                       vformat, 
                                       valuemin, 
                                       valuemax, 
                                       ad_element_id, 
                                       entitytype)
                                       VALUES 
                                      (53016, 
                                       0, 
                                       0, 
                                       'Y', 
                                       TO_TIMESTAMP('2007-11-3 21:38:37:0','YYYY-MM-DD HH:MI:SS:MS'), 
                                       0, 
                                       TO_TIMESTAMP('2007-11-3 21:38:37:0','YYYY-MM-DD HH:MI:SS:MS'), 
                                       0, 
                                       'Tax Category', 
                                       'Tax Category', 
                                       'The Tax Category provides a method of grouping similar taxes.  For example, Sales Tax or Value Added Tax.', 
                                       53002, 
                                       70, 
                                       19, 
                                       NULL, 
                                       NULL, 
                                       'C_TaxCategory_ID', 
                                       'Y', 
                                       10, 
                                       'Y', 
                                       'N', 
                                       NULL, 
                                       NULL, 
                                       NULL, 
                                       NULL, 
                                       NULL, 
                                       211, 
                                       'C');
INSERT INTO ad_process_para (ad_process_para_id, 
                                       ad_client_id, 
                                       ad_org_id, 
                                       isactive, 
                                       created, 
                                       createdby, 
                                       updated, 
                                       updatedby, 
                                       name, 
                                       description, 
                                       help, 
                                       ad_process_id, 
                                       seqno, 
                                       ad_reference_id, 
                                       ad_reference_value_id, 
                                       ad_val_rule_id, 
                                       columnname, 
                                       iscentrallymaintained, 
                                       fieldlength, 
                                       ismandatory, 
                                       isrange, 
                                       defaultvalue, 
                                       defaultvalue2, 
                                       vformat, 
                                       valuemin, 
                                       valuemax, 
                                       ad_element_id, 
                                       entitytype)
                                       VALUES 
                                      (53017, 
                                       0, 
                                       0, 
                                       'Y', 
                                       TO_TIMESTAMP('2007-11-3 21:38:37:0','YYYY-MM-DD HH:MI:SS:MS'), 
                                       0, 
                                       TO_TIMESTAMP('2007-11-3 21:38:37:0','YYYY-MM-DD HH:MI:SS:MS'), 
                                       0, 
                                       'Locator', 
                                       'Warehouse Locator', 
                                       'The Locator indicates where in a Warehouse a product is located.', 
                                       53002, 
                                       80, 
                                       19, 
                                       NULL, 
                                       NULL, 
                                       'M_Locator_ID', 
                                       'Y', 
                                       10, 
                                       'Y', 
                                       'N', 
                                       NULL, 
                                       NULL, 
                                       NULL, 
                                       NULL, 
                                       NULL, 
                                       448, 
                                       'C');
INSERT INTO ad_process_para (ad_process_para_id, 
                                       ad_client_id, 
                                       ad_org_id, 
                                       isactive, 
                                       created, 
                                       createdby, 
                                       updated, 
                                       updatedby, 
                                       name, 
                                       description, 
                                       help, 
                                       ad_process_id, 
                                       seqno, 
                                       ad_reference_id, 
                                       ad_reference_value_id, 
                                       ad_val_rule_id, 
                                       columnname, 
                                       iscentrallymaintained, 
                                       fieldlength, 
                                       ismandatory, 
                                       isrange, 
                                       defaultvalue, 
                                       defaultvalue2, 
                                       vformat, 
                                       valuemin, 
                                       valuemax, 
                                       ad_element_id, 
                                       entitytype)
                                       VALUES 
                                      (53018, 
                                       0, 
                                       0, 
                                       'Y', 
                                       TO_TIMESTAMP('2007-11-3 21:38:37:0','YYYY-MM-DD HH:MI:SS:MS'), 
                                       0, 
                                       TO_TIMESTAMP('2007-11-3 21:38:37:0','YYYY-MM-DD HH:MI:SS:MS'), 
                                       0, 
                                       'Business Partner ', 
                                       'Identifies a Business Partner', 
                                       'A Business Partner is anyone with whom you transact.  This can include Vendor, Customer, Employee or Salesperson', 
                                       53002, 
                                       90, 
                                       19, 
                                       NULL, 
                                       NULL, 
                                       'C_BPartner_ID', 
                                       'Y', 
                                       10, 
                                       'Y', 
                                       'N', 
                                       NULL, 
                                       NULL, 
                                       NULL, 
                                       NULL, 
                                       NULL, 
                                       187, 
                                       'C');
INSERT INTO ad_process_para (ad_process_para_id, 
                                       ad_client_id, 
                                       ad_org_id, 
                                       isactive, 
                                       created, 
                                       createdby, 
                                       updated, 
                                       updatedby, 
                                       name, 
                                       description, 
                                       help, 
                                       ad_process_id, 
                                       seqno, 
                                       ad_reference_id, 
                                       ad_reference_value_id, 
                                       ad_val_rule_id, 
                                       columnname, 
                                       iscentrallymaintained, 
                                       fieldlength, 
                                       ismandatory, 
                                       isrange, 
                                       defaultvalue, 
                                       defaultvalue2, 
                                       vformat, 
                                       valuemin, 
                                       valuemax, 
                                       ad_element_id, 
                                       entitytype)
                                       VALUES 
                                      (53019, 
                                       0, 
                                       0, 
                                       'Y', 
                                       TO_TIMESTAMP('2007-11-3 21:38:37:0','YYYY-MM-DD HH:MI:SS:MS'), 
                                       0, 
                                       TO_TIMESTAMP('2007-11-3 21:38:37:0','YYYY-MM-DD HH:MI:SS:MS'), 
                                       0, 
                                       'Sales Representative', 
                                       'Sales Representative or Company Agent', 
                                       'The Sales Representative indicates the Sales Rep for this Region.  Any Sales Rep must be a valid internal user.', 
                                       53002, 
                                       100, 
                                       18, 
                                       190, 
                                       NULL, 
                                       'SalesRep_ID', 
                                       'Y', 
                                       10, 
                                       'Y', 
                                       'N', 
                                       NULL, 
                                       NULL, 
                                       NULL, 
                                       NULL, 
                                       NULL, 
                                       409, 
                                       'C');
INSERT INTO ad_process_para (ad_process_para_id, 
                                       ad_client_id, 
                                       ad_org_id, 
                                       isactive, 
                                       created, 
                                       createdby, 
                                       updated, 
                                       updatedby, 
                                       name, 
                                       description, 
                                       help, 
                                       ad_process_id, 
                                       seqno, 
                                       ad_reference_id, 
                                       ad_reference_value_id, 
                                       ad_val_rule_id, 
                                       columnname, 
                                       iscentrallymaintained, 
                                       fieldlength, 
                                       ismandatory, 
                                       isrange, 
                                       defaultvalue, 
                                       defaultvalue2, 
                                       vformat, 
                                       valuemin, 
                                       valuemax, 
                                       ad_element_id, 
                                       entitytype)
                                       VALUES 
                                      (53020, 
                                       0, 
                                       0, 
                                       'Y', 
                                       TO_TIMESTAMP('2007-11-3 21:38:37:0','YYYY-MM-DD HH:MI:SS:MS'), 
                                       0, 
                                       TO_TIMESTAMP('2007-11-3 21:38:37:0','YYYY-MM-DD HH:MI:SS:MS'), 
                                       0, 
                                       'Role', 
                                       'Responsibility Role', 
                                       'The Role determines security and access a user who has this Role will have in the System.', 
                                       53002, 
                                       110, 
                                       19, 
                                       NULL, 
                                       NULL, 
                                       'AD_Role_ID', 
                                       'Y', 
                                       10, 
                                       'Y', 
                                       'N', 
                                       NULL, 
                                       NULL, 
                                       NULL, 
                                       NULL, 
                                       NULL, 
                                       123, 
                                       'C');
INSERT INTO ad_process_para (ad_process_para_id, 
                                       ad_client_id, 
                                       ad_org_id, 
                                       isactive, 
                                       created, 
                                       createdby, 
                                       updated, 
                                       updatedby, 
                                       name, 
                                       description, 
                                       help, 
                                       ad_process_id, 
                                       seqno, 
                                       ad_reference_id, 
                                       ad_reference_value_id, 
                                       ad_val_rule_id, 
                                       columnname, 
                                       iscentrallymaintained, 
                                       fieldlength, 
                                       ismandatory, 
                                       isrange, 
                                       defaultvalue, 
                                       defaultvalue2, 
                                       vformat, 
                                       valuemin, 
                                       valuemax, 
                                       ad_element_id, 
                                       entitytype)
                                       VALUES 
                                      (53021, 
                                       0, 
                                       0, 
                                       'Y', 
                                       TO_TIMESTAMP('2007-11-3 21:38:37:0','YYYY-MM-DD HH:MI:SS:MS'), 
                                       0, 
                                       TO_TIMESTAMP('2007-11-3 21:38:37:0','YYYY-MM-DD HH:MI:SS:MS'), 
                                       0, 
                                       'Cash Book', 
                                       'Cash Book for recording petty cash transactions', 
                                       'The Cash Book identifies a unique cash book.  The cash book is used to record cash transactions.', 
                                       53002, 
                                       15, 
                                       19, 
                                       NULL, 
                                       NULL, 
                                       'C_CashBook_ID', 
                                       'Y', 
                                       10, 
                                       'Y', 
                                       'N', 
                                       NULL, 
                                       NULL, 
                                       NULL, 
                                       NULL, 
                                       NULL, 
                                       1463, 
                                       'C');
INSERT INTO ad_process_para (ad_process_para_id, 
                                       ad_client_id, 
                                       ad_org_id, 
                                       isactive, 
                                       created, 
                                       createdby, 
                                       updated, 
                                       updatedby, 
                                       name, 
                                       description, 
                                       help, 
                                       ad_process_id, 
                                       seqno, 
                                       ad_reference_id, 
                                       ad_reference_value_id, 
                                       ad_val_rule_id, 
                                       columnname, 
                                       iscentrallymaintained, 
                                       fieldlength, 
                                       ismandatory, 
                                       isrange, 
                                       defaultvalue, 
                                       defaultvalue2, 
                                       vformat, 
                                       valuemin, 
                                       valuemax, 
                                       ad_element_id, 
                                       entitytype)
                                       VALUES 
                                      (53022, 
                                       0, 
                                       0, 
                                       'Y', 
                                       TO_TIMESTAMP('2007-11-3 21:38:37:0','YYYY-MM-DD HH:MI:SS:MS'), 
                                       0, 
                                       TO_TIMESTAMP('2007-11-3 21:38:37:0','YYYY-MM-DD HH:MI:SS:MS'), 
                                       0, 
                                       'Name', 
                                       'Alphanumeric identifier of the entity', 
                                       'The name of an entity (record) is used as an default search option in addition to the search key. The name is up to 60 characters in length.', 
                                       53002, 
                                       130, 
                                       10, 
                                       NULL, 
                                       NULL, 
                                       'Name', 
                                       'Y', 
                                       60, 
                                       'Y', 
                                       'N', 
                                       NULL, 
                                       NULL, 
                                       NULL, 
                                       NULL, 
                                       NULL, 
                                       469, 
                                       'C');
INSERT INTO ad_process_para (ad_process_para_id, 
                                       ad_client_id, 
                                       ad_org_id, 
                                       isactive, 
                                       created, 
                                       createdby, 
                                       updated, 
                                       updatedby, 
                                       name, 
                                       description, 
                                       help, 
                                       ad_process_id, 
                                       seqno, 
                                       ad_reference_id, 
                                       ad_reference_value_id, 
                                       ad_val_rule_id, 
                                       columnname, 
                                       iscentrallymaintained, 
                                       fieldlength, 
                                       ismandatory, 
                                       isrange, 
                                       defaultvalue, 
                                       defaultvalue2, 
                                       vformat, 
                                       valuemin, 
                                       valuemax, 
                                       ad_element_id, 
                                       entitytype)
                                       VALUES 
                                      (53023, 
                                       0, 
                                       0, 
                                       'Y', 
                                       TO_TIMESTAMP('2007-11-3 21:38:37:0','YYYY-MM-DD HH:MI:SS:MS'), 
                                       0, 
                                       TO_TIMESTAMP('2007-11-3 21:38:37:0','YYYY-MM-DD HH:MI:SS:MS'), 
                                       0, 
                                       'Host Address', 
                                       'Host Address URL or DNS', 
                                       'The Host Address identifies the URL or DNS of the target host', 
                                       53002, 
                                       140, 
                                       10, 
                                       NULL, 
                                       NULL, 
                                       'HostAddress', 
                                       'Y', 
                                       60, 
                                       'Y', 
                                       'N', 
                                       'http://', 
                                       NULL, 
                                       NULL, 
                                       NULL, 
                                       NULL, 
                                       1398, 
                                       'C');
INSERT INTO ad_process_para (ad_process_para_id, 
                                       ad_client_id, 
                                       ad_org_id, 
                                       isactive, 
                                       created, 
                                       createdby, 
                                       updated, 
                                       updatedby, 
                                       name, 
                                       description, 
                                       help, 
                                       ad_process_id, 
                                       seqno, 
                                       ad_reference_id, 
                                       ad_reference_value_id, 
                                       ad_val_rule_id, 
                                       columnname, 
                                       iscentrallymaintained, 
                                       fieldlength, 
                                       ismandatory, 
                                       isrange, 
                                       defaultvalue, 
                                       defaultvalue2, 
                                       vformat, 
                                       valuemin, 
                                       valuemax, 
                                       ad_element_id, 
                                       entitytype)
                                       VALUES 
                                      (53024, 
                                       0, 
                                       0, 
                                       'Y', 
                                       TO_TIMESTAMP('2007-11-3 21:38:37:0','YYYY-MM-DD HH:MI:SS:MS'), 
                                       0, 
                                       TO_TIMESTAMP('2007-11-3 21:38:37:0','YYYY-MM-DD HH:MI:SS:MS'), 
                                       0, 
                                       'Discount Schema', 
                                       'Schema to calculate the trade discount percentage', 
                                       'After calculation of the (standard) price, the trade discount percentage is calculated and applied resulting in the final price.', 
                                       53002, 
                                       25, 
                                       19, 
                                       NULL, 
                                       NULL, 
                                       'M_DiscountSchema_ID', 
                                       'Y', 
                                       10, 
                                       'Y', 
                                       'N', 
                                       NULL, 
                                       NULL, 
                                       NULL, 
                                       NULL, 
                                       NULL, 
                                       1714, 
                                       'C');
INSERT INTO ad_process_para (ad_process_para_id, 
                                       ad_client_id, 
                                       ad_org_id, 
                                       isactive, 
                                       created, 
                                       createdby, 
                                       updated, 
                                       updatedby, 
                                       name, 
                                       description, 
                                       help, 
                                       ad_process_id, 
                                       seqno, 
                                       ad_reference_id, 
                                       ad_reference_value_id, 
                                       ad_val_rule_id, 
                                       columnname, 
                                       iscentrallymaintained, 
                                       fieldlength, 
                                       ismandatory, 
                                       isrange, 
                                       defaultvalue, 
                                       defaultvalue2, 
                                       vformat, 
                                       valuemin, 
                                       valuemax, 
                                       ad_element_id, 
                                       entitytype)
                                       VALUES 
                                      (53025, 
                                       0, 
                                       0, 
                                       'Y', 
                                       TO_TIMESTAMP('2007-11-3 21:38:38:0','YYYY-MM-DD HH:MI:SS:MS'), 
                                       0, 
                                       TO_TIMESTAMP('2007-11-3 21:38:38:0','YYYY-MM-DD HH:MI:SS:MS'), 
                                       0, 
                                       'Purchase Price List Version', 
                                       NULL, 
                                       NULL, 
                                       53002, 
                                       30, 
                                       18, 
                                       188, 
                                       NULL, 
                                       'PriceList_Version_ID', 
                                       'Y', 
                                       10, 
                                       'Y', 
                                       'N', 
                                       NULL, 
                                       NULL, 
                                       NULL, 
                                       NULL, 
                                       NULL, 
                                       450, 
                                       'C');
INSERT INTO ad_process_para (ad_process_para_id, 
                                       ad_client_id, 
                                       ad_org_id, 
                                       isactive, 
                                       created, 
                                       createdby, 
                                       updated, 
                                       updatedby, 
                                       name, 
                                       description, 
                                       help, 
                                       ad_process_id, 
                                       seqno, 
                                       ad_reference_id, 
                                       ad_reference_value_id, 
                                       ad_val_rule_id, 
                                       columnname, 
                                       iscentrallymaintained, 
                                       fieldlength, 
                                       ismandatory, 
                                       isrange, 
                                       defaultvalue, 
                                       defaultvalue2, 
                                       vformat, 
                                       valuemin, 
                                       valuemax, 
                                       ad_element_id, 
                                       entitytype)
                                       VALUES 
                                      (53026, 
                                       0, 
                                       0, 
                                       'Y', 
                                       TO_TIMESTAMP('2007-11-3 21:38:38:0','YYYY-MM-DD HH:MI:SS:MS'), 
                                       0, 
                                       TO_TIMESTAMP('2007-11-3 21:38:38:0','YYYY-MM-DD HH:MI:SS:MS'), 
                                       0, 
                                       'UserPIN', 
                                       NULL, 
                                       NULL, 
                                       53002, 
                                       120, 
                                       10, 
                                       NULL, 
                                       NULL, 
                                       'UserPIN', 
                                       'Y', 
                                       10, 
                                       'Y', 
                                       'N', 
                                       NULL, 
                                       NULL, 
                                       NULL, 
                                       NULL, 
                                       NULL, 
                                       52023, 
                                       'C');


--
-- ad_treenodemm
-- 

INSERT INTO ad_treenodemm (ad_tree_id, 
                                     node_id, 
                                     ad_client_id, 
                                     ad_org_id, 
                                     isactive, 
                                     created, 
                                     createdby, 
                                     updated, 
                                     updatedby, 
                                     parent_id, 
                                     seqno)
                                     VALUES 
                                    (10, 
                                     53013, 
                                     0, 
                                     0, 
                                     'Y', 
                                     TO_TIMESTAMP('2007-11-3 21:38:36:665','YYYY-MM-DD HH:MI:SS:MS'), 
                                     0, 
                                     TO_TIMESTAMP('2007-11-3 21:38:36:665','YYYY-MM-DD HH:MI:SS:MS'), 
                                     0, 
                                     52001, 
                                     5);

INSERT INTO AD_Process_Access (AD_Client_ID,AD_Org_ID,IsReadWrite,Created,AD_Process_ID,CreatedBy,Updated,UpdatedBy,IsActive,AD_Role_ID) VALUES (11,0,'Y',TO_TIMESTAMP('2007-11-05 14:26:09','YYYY-MM-DD HH24:MI:SS'),53002,100,TO_TIMESTAMP('2007-11-05 14:26:09','YYYY-MM-DD HH24:MI:SS'),100,'Y',102);