-- DROP VIEW RV_C_BankStatement;
CREATE OR REPLACE  VIEW RV_C_BankStatement AS
 SELECT
 bsl.C_BANKSTATEMENTLINE_ID,
 bsl.AD_CLIENT_ID,
 bsl.AD_ORG_ID,
 bsl.ISACTIVE,
 bsl.CREATED,
 bsl.CREATEDBY,
 bsl.UPDATED,
 bsl.UPDATEDBY,
 bsl.LINE,
 bsl.DESCRIPTION,
 bsl.ISREVERSAL,
 bsl.C_PAYMENT_ID,
 bsl.VALUTADATE,
 bsl.DATEACCT,
 bsl.C_CURRENCY_ID,
 bsl.TRXAMT,
 bsl.STMTAMT,
 bsl.C_CHARGE_ID,
 bsl.CHARGEAMT,
 bsl.INTERESTAMT,
 bsl.MEMO,
 bsl.REFERENCENO,
 bsl.ISMANUAL,
 bsl.EFTTRXID,
 bsl.EFTTRXTYPE,
 bsl.EFTMEMO,
 bsl.EFTPAYEE,
 bsl.EFTPAYEEACCOUNT,
 bsl.CREATEPAYMENT,
 bsl.STATEMENTLINEDATE,
 bsl.EFTSTATEMENTLINEDATE,
 bsl.EFTVALUTADATE,
 bsl.EFTREFERENCE,
 bsl.EFTCURRENCY,
 bsl.EFTAMT,
 bsl.EFTCHECKNO,
 bsl.MATCHSTATEMENT,
 bsl.C_BPARTNER_ID,
 bsl.C_INVOICE_ID,
 bsl.PROCESSED,
 bs.C_BANKSTATEMENT_ID,
 bs.C_BankAccount_ID,
 bs.name,
 bs.description AS Note,
 bs.DocStatus,
 bs.BeginningBalance,
 bs.StatementDifference,
 bs.EndingBalance,
 bs.StatementDate,
 bs.EftStatementDate,
 bs.EftStatementReference,
 ba.C_Bank_ID,
 p.DateTrx,
 p.C_DocType_ID,
 p.TenderType,
 p.Payamt,
 o.C_Order_ID,
 o.DateOrdered,
 o.Grandtotal,
 o.C_POS_ID,
 o.SalesRep_ID,
 o.AmountRefunded,
 o.AmountTendered,
 i.Dateinvoiced,
 i.IsPaid,
 i.GrandTotal AS InvoiceAmt
 FROM C_BANKSTATEMENTLINE bsl
 INNER JOIN C_BANKSTATEMENT bs ON bsl.C_BANKSTATEMENT_ID = bs.C_BANKSTATEMENT_ID
 LEFT JOIN C_BankAccount ba ON bs.C_BankAccount_ID = ba.C_BankAccount_ID
 LEFT JOIN C_Payment p ON bsl.C_Payment_ID=p.C_Payment_ID
 LEFT JOIN C_Order o ON p.C_Order_ID=o.C_Order_ID
 LEFT JOIN C_Invoice i ON bsl.C_Invoice_ID = i.C_Invoice_ID;