CREATE OR REPLACE VIEW RV_PRODUCTIONLINE 
(M_PRODUCTIONLINE_ID,
AD_CLIENT_ID,
AD_ORG_ID,
ISACTIVE,
CREATED,
CREATEDBY,
UPDATED,
UPDATEDBY,
M_PRODUCTIONPLAN_ID,
LINE,
M_PRODUCT_ID,
MOVEMENTQTY,
M_LOCATOR_ID,
DESCRIPTION,
M_ATTRIBUTESETINSTANCE_ID,
PROCESSED,
M_PRODUCTION_ID,
PLANNEDQTY,
QTYUSED,
ISENDPRODUCT,
QTYRESERVED,
PICKEDQTY,
M_PRODUCT_CATEGORY_ID,
PRODUCTTYPE,
PRODUCTVALUE,
PRODUCTNAME)

AS 
 SELECT pl.m_productionline_id,
    pl.ad_client_id,
    pl.ad_org_id,
    pl.isactive,
    pl.created,
    pl.createdby,
    pl.updated,
    pl.updatedby,
    pl.m_productionplan_id,
    pl.line,
    pl.m_product_id,
    pl.movementqty,
    pl.m_locator_id,
    pl.description,
    pl.m_attributesetinstance_id,
    pl.processed,
    pl.m_production_id,
    pl.plannedqty,
    pl.qtyused,
    pl.isendproduct,
    pl.qtyreserved,
    pl.pickedqty,
    p.m_product_category_id,
    p.producttype,
    p.value AS productvalue,
    p.name AS productname
   FROM m_productionline pl
   INNER JOIN m_product p ON pl.m_product_id = p.m_product_id;