-- Sep 24, 2009 12:30:51 PM COT
-- FR2462571-Invalid characters in 3.5.2a seed - ad_field
UPDATE AD_Window_Trl SET Help='It is a list of all the subassemblies, intermediates, parts and raw material that go into a parent assembly showing the quantity of each required to make an assembly. There are a variety of display formats of bill of material, including single level bill of material, indented bill of material, modular (planning), costed bill of material, etc. May also be called "formula", "recipe", "ingredients list" in certain industries.
It answers the question, what are the components of the product?',Updated=TO_TIMESTAMP('2009-09-24 12:30:51','YYYY-MM-DD HH24:MI:SS'),UpdatedBy=100 WHERE AD_Window_ID=53006 AND AD_Language='es_MX'
;

-- Sep 24, 2009 12:33:50 PM COT
UPDATE AD_Field_Trl SET Help='The Valid From date indicates the first day of a date range.
When you enter dates in the fields Valid From - To we give the the period of time where this operation will have to be considered for the elaboration of the product.',Updated=TO_TIMESTAMP('2009-09-24 12:33:50','YYYY-MM-DD HH24:MI:SS'),UpdatedBy=100 WHERE AD_Field_ID=53380 AND AD_Language='es_MX'
;

-- Sep 24, 2009 12:35:00 PM COT
UPDATE AD_Field_Trl SET Help='The Valid To date indicates the last day of a date range
When you enter dates in the fields Valid From - To we give the the period of time where this operation will have to be considered for the elaboration of the product.',Updated=TO_TIMESTAMP('2009-09-24 12:35:00','YYYY-MM-DD HH24:MI:SS'),UpdatedBy=100 WHERE AD_Field_ID=53381 AND AD_Language='es_MX'
;

-- Sep 24, 2009 12:36:13 PM COT
UPDATE AD_Field_Trl SET Help='Indicates the Date an item was ordered.
Date Ordered is the date when the order was generated. If the MO is created manually the default date ordered is the system date. If the MO was generated by MRP the default date ordered is the day of the MRP process.',Updated=TO_TIMESTAMP('2009-09-24 12:36:13','YYYY-MM-DD HH24:MI:SS'),UpdatedBy=100 WHERE AD_Field_ID=54139 AND AD_Language='es_MX'
;

-- Sep 24, 2009 12:36:43 PM COT
UPDATE AD_Field_Trl SET Help='The Date Promised indicates the date, if any, that an Order was promised for.
Date Promised Is the date we commit to give the order to the warehouse. If the MO is created manually the default date promised is the system date. If the MO was generated by MRP this date is filled automatically using its algorithm calculation.',Updated=TO_TIMESTAMP('2009-09-24 12:36:43','YYYY-MM-DD HH24:MI:SS'),UpdatedBy=100 WHERE AD_Field_ID=54140 AND AD_Language='es_MX'
;

