DROP VIEW RV_PP_ORDER_COST;
CREATE OR REPLACE VIEW RV_PP_ORDER_COST AS
 SELECT o.ad_client_id,
    o.ad_org_id,
    o.pp_order_id,
    o.documentno,
    o.docstatus,
    o.created,
    o.createdby,
    o.updated,
    o.updatedby,
    o.isactive,
    o.m_warehouse_id,
    o.m_product_id AS parent_id,
    p.m_product_category_id,
    o.qtyentered,
    o.qtyreject,
    o.qtyscrap,
    o.qtybatchs,
    o.qtybatchsize,
    o.dateordered,
    o.datepromised,
    o.datestart,
    o.datestartschedule,
    o.datefinish,
    o.datefinishschedule,
    o.dateconfirm,
    o.datedelivered,
    o.lot,
    o.pp_product_bom_id,
    o.ad_workflow_id,
    o.weight,
    o.c_doctypetarget_id,
    o.m_attributesetinstance_id,
    o.planner_id,
    o.priorityrule,
    o.ad_orgtrx_id,
    o.user1_id,
    o.user2_id,
    o.c_doctype_id,
    o.line,
    o.description,
    o.s_resource_id,
    o.floatbefored,
    o.floatafter,
    o.c_uom_id,
    o.qtyordered,
    o.qtydelivered,
    o.yield,
    o.c_project_id,
    o.c_campaign_id,
    o.c_activity_id,
    o.isapproved,
    o.isprinted,
    o.isselected,
    o.processed,
    o.assay,
    o.isqtypercentage,
    o.ordertype,
    o.issotrx,
    o.scheduletype,
    o.serno,
    ocd.c_acctschema_id,
    ocd.m_costtype_id,
    ocd.m_costelement_id,
    ocd.m_product_id,
    ocd.qty,
    ocd.currentcostprice,
    ocd.currentcostpricell,
    ocd.qtyrequired,
    ocd.expectedcost,
    ocd.expectedcostll,
    ocd.expectedcost + ocd.expectedcostll AS expectedtotalcost,
    ocd.cumulatedqty,
    ocd.cumulatedamt,
    ocd.cumulatedamtll,
    ocd.usagevariance,
    ocd.methodchangevariance,
    ocd.ratevariance,
    ocd.mixvariance,
    ocd.amt,
    ocd.amtll,
    ocd.cumulatedamt + ocd.usagevariance + ocd.methodchangevariance + ocd.ratevariance + ocd.mixvariance AS totalamt
   FROM RV_PP_ORDER o
     JOIN rv_pp_order_costdetail ocd ON o.pp_order_id = ocd.pp_order_id
     JOIN m_product p ON p.m_product_id = o.m_product_id;