-- Aug 21, 2009 5:16:47 PM EEST
-- BF: 2836887 - Not well Formed XML
UPDATE AD_Field SET Help='The Valid To date indicates the last day of a date range
When you enter dates in the fields Valid From - To we give the the period of time where this operation will have to be considered for the elaboration of the product.',Updated=TO_DATE('2009-08-21 17:16:47','YYYY-MM-DD HH24:MI:SS'),UpdatedBy=100 WHERE AD_Field_ID=53381
;

-- Aug 21, 2009 5:16:47 PM EEST
-- BF: 2836887 - Not well Formed XML
UPDATE AD_Field_Trl SET IsTranslated='N' WHERE AD_Field_ID=53381
;

-- Aug 21, 2009 5:18:32 PM EEST
-- BF: 2836887 - Not well Formed XML
UPDATE AD_Field SET Help='The Valid From date indicates the first day of a date range.
When you enter dates in the fields Valid From - To we give the the period of time where this operation will have to be considered for the elaboration of the product.',Updated=TO_DATE('2009-08-21 17:18:32','YYYY-MM-DD HH24:MI:SS'),UpdatedBy=100 WHERE AD_Field_ID=53380
;

-- Aug 21, 2009 5:18:32 PM EEST
-- BF: 2836887 - Not well Formed XML
UPDATE AD_Field_Trl SET IsTranslated='N' WHERE AD_Field_ID=53380
;

-- Aug 21, 2009 5:21:58 PM EEST
-- BF: 2836887 - Not well Formed XML
UPDATE AD_Field SET Help='Indicates the Date an item was ordered.
Date Ordered is the date when the order was generated. If the MO is created manually the default date ordered is the system date. If the MO was generated by MRP the default date ordered is the day of the MRP process.',Updated=TO_DATE('2009-08-21 17:21:58','YYYY-MM-DD HH24:MI:SS'),UpdatedBy=100 WHERE AD_Field_ID=54139
;

-- Aug 21, 2009 5:21:58 PM EEST
-- BF: 2836887 - Not well Formed XML
UPDATE AD_Field_Trl SET IsTranslated='N' WHERE AD_Field_ID=54139
;

-- Aug 21, 2009 5:22:59 PM EEST
-- BF: 2836887 - Not well Formed XML
UPDATE AD_Field SET Help='The Date Promised indicates the date, if any, that an Order was promised for.
Date Promised Is the date we commit to give the order to the warehouse. If the MO is created manually the default date promised is the system date. If the MO was generated by MRP this date is filled automatically using its algorithm calculation.',Updated=TO_DATE('2009-08-21 17:22:59','YYYY-MM-DD HH24:MI:SS'),UpdatedBy=100 WHERE AD_Field_ID=54140
;

-- Aug 21, 2009 5:22:59 PM EEST
-- BF: 2836887 - Not well Formed XML
UPDATE AD_Field_Trl SET IsTranslated='N' WHERE AD_Field_ID=54140
;

-- Aug 21, 2009 5:27:04 PM EEST
-- BF: 2836887 - Not well Formed XML
UPDATE AD_Window SET Help='It is a list of all the subassemblies, intermediates, parts and raw material that go into a parent assembly showing the quantity of each required to make an assembly. There are a variety of display formats of bill of material, including single level bill of material, indented bill of material, modular (planning), costed bill of material, etc. May also be called "formula", "recipe", "ingredients list" in certain industries.
It answers the question, what are the components of the product?',Updated=TO_DATE('2009-08-21 17:27:04','YYYY-MM-DD HH24:MI:SS'),UpdatedBy=100 WHERE AD_Window_ID=53006
;

-- Aug 21, 2009 5:27:04 PM EEST
-- BF: 2836887 - Not well Formed XML
UPDATE AD_Window_Trl SET IsTranslated='N' WHERE AD_Window_ID=53006
;

