ALTER TABLE ad_view_trl ADD CONSTRAINT ad_view_trl_key PRIMARY KEY (ad_view_id, ad_language);
ALTER TABLE ad_view_column_trl ADD CONSTRAINT ad_view_column_trl_key PRIMARY KEY (ad_view_column_id, ad_language);

ALTER TABLE ad_browse_trl ADD CONSTRAINT ad_browse_trl_key PRIMARY KEY (ad_browse_id, ad_language);
ALTER TABLE ad_browse_field_trl DROP CONSTRAINT ad_browse_field_trl_key;
ALTER TABLE ad_browse_field_trl ADD CONSTRAINT ad_browse_field_trl_key PRIMARY KEY (ad_browse_field_id, ad_language);
ALTER TABLE ad_browse_access ADD CONSTRAINT ad_browse_access_key PRIMARY KEY (ad_browse_id, ad_role_id);

ALTER TABLE AD_Element ADD CONSTRAINT ADReference_ADElement FOREIGN KEY (AD_Reference_ID) REFERENCES AD_Reference DEFERRABLE INITIALLY DEFERRED;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
ALTER TABLE AD_Element ADD CONSTRAINT ADReferenceValue_ADElement FOREIGN KEY (AD_Reference_Value_ID) REFERENCES AD_Reference DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE AD_Browse ADD CONSTRAINT EntityT_ADBrowse FOREIGN KEY (EntityType) REFERENCES AD_EntityType DEFERRABLE INITIALLY DEFERRED;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
ALTER TABLE AD_Browse ADD CONSTRAINT ADProcess_ADBrowse FOREIGN KEY (AD_Process_ID) REFERENCES AD_Process DEFERRABLE INITIALLY DEFERRED;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
ALTER TABLE AD_Browse ADD CONSTRAINT ADView_ADBrowse FOREIGN KEY (AD_View_ID) REFERENCES AD_View DEFERRABLE INITIALLY DEFERRED;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
ALTER TABLE AD_Browse_Access ADD CONSTRAINT ADBrowse_ADBrowseAccess FOREIGN KEY (AD_Browse_ID) REFERENCES AD_Browse DEFERRABLE INITIALLY DEFERRED;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
ALTER TABLE AD_Browse_Access ADD CONSTRAINT ADRole_ADBrowseAccess FOREIGN KEY (AD_Role_ID) REFERENCES AD_Role DEFERRABLE INITIALLY DEFERRED;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
ALTER TABLE AD_Browse_Field ADD CONSTRAINT ADBrowse_ADBrowseField FOREIGN KEY (AD_Browse_ID) REFERENCES AD_Browse DEFERRABLE INITIALLY DEFERRED;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
ALTER TABLE AD_Browse_Field ADD CONSTRAINT ADElement_ADBrowseField FOREIGN KEY (AD_Element_ID) REFERENCES AD_Element DEFERRABLE INITIALLY DEFERRED;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
ALTER TABLE AD_Browse_Field ADD CONSTRAINT EntityT_ADBrowseField FOREIGN KEY (EntityType) REFERENCES AD_EntityType DEFERRABLE INITIALLY DEFERRED;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
ALTER TABLE AD_Browse_Field ADD CONSTRAINT ADReference_ADBrowseField FOREIGN KEY (AD_Reference_ID) REFERENCES AD_Reference DEFERRABLE INITIALLY DEFERRED;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
ALTER TABLE AD_Browse_Field ADD CONSTRAINT ADReferenceValue_ADBrowseField FOREIGN KEY (AD_Reference_Value_ID) REFERENCES AD_Reference DEFERRABLE INITIALLY DEFERRED;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
ALTER TABLE AD_Browse_Field ADD CONSTRAINT ADViewColumn_ADBrowseField FOREIGN KEY (AD_View_Column_ID) REFERENCES AD_View_Column DEFERRABLE INITIALLY DEFERRED;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
ALTER TABLE AD_Browse_Field ADD CONSTRAINT AxisColumn_ADBrowseField FOREIGN KEY (Axis_Column_ID) REFERENCES AD_View_Column DEFERRABLE INITIALLY DEFERRED;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
ALTER TABLE AD_Browse_Field ADD CONSTRAINT AxisParentColumn_ADBrowseField FOREIGN KEY (Axis_Parent_Column_ID) REFERENCES AD_View_Column DEFERRABLE INITIALLY DEFERRED;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
ALTER TABLE AD_Browse_Field_Trl ADD CONSTRAINT ADBrowseField_ADBrowseFieldTrl FOREIGN KEY (AD_Browse_Field_ID) REFERENCES AD_Browse_Field DEFERRABLE INITIALLY DEFERRED;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
ALTER TABLE AD_Browse_Field_Trl ADD CONSTRAINT ADLangu_ADBrowseFieldTrl FOREIGN KEY (AD_Language) REFERENCES AD_Language DEFERRABLE INITIALLY DEFERRED;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
ALTER TABLE AD_Browse_Trl ADD CONSTRAINT ADLangu_ADBrowseTrl FOREIGN KEY (AD_Language) REFERENCES AD_Language DEFERRABLE INITIALLY DEFERRED;     
ALTER TABLE AD_Browse_Trl ADD CONSTRAINT ADBrowse_ADBrowseTrl FOREIGN KEY (AD_Browse_ID) REFERENCES AD_Browse DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE AD_Menu ADD CONSTRAINT ADBrowse_ADMenu FOREIGN KEY (AD_Browse_ID) REFERENCES AD_Browse DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE AD_Package_Exp_Detail ADD CONSTRAINT ADBrowse_ADPackageExpDetail FOREIGN KEY (AD_Browse_ID) REFERENCES AD_Browse DEFERRABLE INITIALLY DEFERRED;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
ALTER TABLE AD_Package_Exp_Detail ADD CONSTRAINT ADPackageExp_ADPackageExpDetai FOREIGN KEY (AD_Package_Exp_ID) REFERENCES AD_Package_Exp DEFERRABLE INITIALLY DEFERRED;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
ALTER TABLE AD_Package_Exp_Detail ADD CONSTRAINT ADView_ADPackageExpDetail FOREIGN KEY (AD_View_ID) REFERENCES AD_View DEFERRABLE INITIALLY DEFERRED;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
ALTER TABLE AD_View_Column ADD CONSTRAINT ADColumn_ADViewColumn FOREIGN KEY (AD_Column_ID) REFERENCES AD_Column DEFERRABLE INITIALLY DEFERRED;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
ALTER TABLE AD_View_Column ADD CONSTRAINT EntityT_ADViewColumn FOREIGN KEY (EntityType) REFERENCES AD_EntityType DEFERRABLE INITIALLY DEFERRED;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
ALTER TABLE AD_View_Column ADD CONSTRAINT ADView_ADViewColumn FOREIGN KEY (AD_View_ID) REFERENCES AD_View DEFERRABLE INITIALLY DEFERRED;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
ALTER TABLE AD_View_Column ADD CONSTRAINT ADViewDefinition_ADViewColumn FOREIGN KEY (AD_View_Definition_ID) REFERENCES AD_View_Definition DEFERRABLE INITIALLY DEFERRED;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
ALTER TABLE AD_View_Column_Trl ADD CONSTRAINT ADLangu_ADViewColumnTrl FOREIGN KEY (AD_Language) REFERENCES AD_Language DEFERRABLE INITIALLY DEFERRED;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
ALTER TABLE AD_View_Column_Trl ADD CONSTRAINT ADViewColumn_ADViewColumnTrl FOREIGN KEY (AD_View_Column_ID) REFERENCES AD_View_Column DEFERRABLE INITIALLY DEFERRED;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
ALTER TABLE AD_View_Definition ADD CONSTRAINT ADTable_ADViewDefinition FOREIGN KEY (AD_Table_ID) REFERENCES AD_Table DEFERRABLE INITIALLY DEFERRED;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
ALTER TABLE AD_View_Definition ADD CONSTRAINT ADView_ADViewDefinition FOREIGN KEY (AD_View_ID) REFERENCES AD_View DEFERRABLE INITIALLY DEFERRED;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
ALTER TABLE AD_View_Trl ADD CONSTRAINT ADLangu_ADViewTrl FOREIGN KEY (AD_Language) REFERENCES AD_Language DEFERRABLE INITIALLY DEFERRED;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
ALTER TABLE AD_View_Trl ADD CONSTRAINT ADView_ADViewTrl FOREIGN KEY (AD_View_ID) REFERENCES AD_View DEFERRABLE INITIALLY DEFERRED;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
ALTER TABLE AD_WF_Node ADD CONSTRAINT ADBrowse_ADWFNode FOREIGN KEY (AD_Browse_ID) REFERENCES AD_Browse DEFERRABLE INITIALLY DEFERRED;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
ALTER TABLE AD_WF_Node ADD CONSTRAINT ADView_ADWFNode FOREIGN KEY (AD_View_ID) REFERENCES AD_View DEFERRABLE INITIALLY DEFERRED;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         

--DELETE FROM T_Selection_Browse;
--DROP TABLE t_selection_browse;
CREATE TABLE t_selection_browse
(
  ad_pinstance_id numeric,
  t_selection_id numeric,
  columnname character varying(255) ,
  value_string character varying(255),
  value_date timestamp without time zone,
  value_number numeric,
  info character varying(60)
);

ALTER TABLE t_selection_browse ADD CONSTRAINT t_selection_browse_key PRIMARY KEY (ad_pinstance_id, t_selection_id, columnname);