ALTER TABLE I_INVOICE MODIFY(taxindicator NVARCHAR2(10));

ALTER TABLE I_ORDER MODIFY(taxindicator NVARCHAR2(10));

UPDATE AD_COLUMN
   SET fieldlength = 10
 WHERE ad_column_id IN (8991, 9186);

COMMIT;