ALTER TABLE PP_MRP ADD CONSTRAINT DDOrder_PPMRP FOREIGN KEY (DD_Order_ID) REFERENCES DD_ORDER;

ALTER TABLE PP_MRP ADD CONSTRAINT DDOrderLine_PPMRP FOREIGN KEY (DD_OrderLine_ID) REFERENCES DD_ORDERLINE;

ALTER TABLE PP_ORDER_BOMLINE ADD CONSTRAINT ADUser_PPOrderBOMLine FOREIGN KEY (AD_User_ID) REFERENCES AD_USER;

