ALTER TABLE AD_Ref_TABLE ADD isalert CHAR(1) DEFAULT 'N' NOT NULL;

ALTER TABLE AD_Ref_TABLE ADD displaysql VARCHAR2(100);

ALTER TABLE AD_Ref_TABLE ADD isdisplayidentifier CHAR(1) DEFAULT 'N' NOT NULL;
