SET DEFINE OFF
SET SQLBLANKLINES ON
SET SCAN OFF

-- May 18, 2010 11:24:10 AM EEST
-- I forgot to set the DICTIONARY_ID_COMMENTS System Configurator
ALTER TABLE M_CostQueue ADD DateAcct DATE DEFAULT NULL 
;

