SELECT SUBSTR('asdfg',1,2) FROM SysIBM.SysDummy1;



SELECT TIMESTAMP('2006-01-22-12.00.00.000000') FROM SysIBM.SysDummy1;

SELECT CURRENT TIMESTAMP FROM SysIBM.SysDummy1;

SELECT USER FROM SysIBM.SysDummy1;
SELECT CURRENT USER FROM SysIBM.SysDummy1;
SELECT SYSTEM_USER FROM SysIBM.SysDummy1;

SELECT CURRENT SERVER FROM SysIBM.SysDummy1;
SELECT CURRENT SCHEMA FROM SysIBM.SysDummy1;



SELECT CURRENT TIMESTAMP FROM SysIBM.SysDummy1;
SELECT CURRENT TIMESTAMP FROM SysIBM.SysDummy1;




SELECT CURRENT TIMESTAMP FROM SysIBM.SysDummy1;

