drop table PP_WF_NODE_ASSET
;

CREATE TABLE PP_WF_NODE_ASSET
(
    PP_WF_NODE_ASSET_ID NUMBER(10,0) NOT NULL ENABLE,
    --
    AD_CLIENT_ID NUMBER(10,0) NOT NULL ENABLE,
    AD_ORG_ID NUMBER(10,0) NOT NULL ENABLE,
    CREATED DATE NOT NULL ENABLE,
    CREATEDBY NUMBER(10,0) NOT NULL ENABLE,
    UPDATED DATE NOT NULL ENABLE,
    UPDATEDBY NUMBER(10,0) NOT NULL ENABLE,
    ISACTIVE CHAR(1 BYTE) NOT NULL ENABLE,
    --
    AD_WF_NODE_ID NUMBER(10,0) NOT NULL ENABLE,
    A_ASSET_ID NUMBER(10,0) NOT NULL ENABLE,
    SEQNO NUMBER(10,0) NOT NULL ENABLE,
    --
    CHECK (IsActive IN ('Y','N')) ENABLE,
    CONSTRAINT PP_WF_NODE_ASSET_KEY PRIMARY KEY (PP_WF_NODE_ASSET_ID) ENABLE,
    CONSTRAINT AASSET_PPWFNODEASSET FOREIGN KEY (A_ASSET_ID) REFERENCES A_ASSET (A_ASSET_ID) ENABLE,
    CONSTRAINT ADWFNODE_PPWFNODEASSET FOREIGN KEY (AD_WF_NODE_ID) REFERENCES AD_WF_NODE (AD_WF_NODE_ID) ENABLE
)
;

-- 29.08.2008 18:32:06 EEST
-- 
UPDATE AD_Column SET IsKey='N', IsMandatory='Y',Updated=TO_DATE('2008-08-29 18:32:06','YYYY-MM-DD HH24:MI:SS'),UpdatedBy=0 WHERE AD_Column_ID=53300
;

-- 29.08.2008 18:32:28 EEST
-- 
UPDATE AD_Column SET IsKey='Y', IsUpdateable='N',Updated=TO_DATE('2008-08-29 18:32:28','YYYY-MM-DD HH24:MI:SS'),UpdatedBy=0 WHERE AD_Column_ID=53299
;
