-- Jun 17, 2013 4:44:12 PM EEST
-- I forgot to set the DICTIONARY_ID_COMMENTS System Configurator
UPDATE AD_Column SET FieldLength=255,Updated=TO_DATE('2013-06-17 16:44:12','YYYY-MM-DD HH24:MI:SS'),UpdatedBy=100
WHERE AD_Element_ID=1682 AND ColumnName='EntityType'
;

ALTER TABLE AD_Table MODIFY EntityType VARCHAR2(255);
ALTER TABLE AD_Column MODIFY EntityType VARCHAR2(255);
ALTER TABLE AD_Reference MODIFY EntityType VARCHAR2(255);
ALTER TABLE AD_Ref_Table MODIFY EntityType VARCHAR2(255);
ALTER TABLE AD_Ref_List MODIFY EntityType VARCHAR2(255);
ALTER TABLE AD_Window MODIFY EntityType VARCHAR2(255);
ALTER TABLE AD_Tab MODIFY EntityType VARCHAR2(255);
ALTER TABLE AD_Field MODIFY EntityType VARCHAR2(255);
ALTER TABLE AD_Val_Rule MODIFY EntityType VARCHAR2(255);
ALTER TABLE AD_Message MODIFY EntityType VARCHAR2(255);
ALTER TABLE AD_Menu MODIFY EntityType VARCHAR2(255);
ALTER TABLE AD_Workflow MODIFY EntityType VARCHAR2(255);
ALTER TABLE AD_Task MODIFY EntityType VARCHAR2(255);
ALTER TABLE AD_WF_Node MODIFY EntityType VARCHAR2(255);
ALTER TABLE AD_WF_NodeNext MODIFY EntityType VARCHAR2(255);
ALTER TABLE AD_Element MODIFY EntityType VARCHAR2(255);
ALTER TABLE AD_Process MODIFY EntityType VARCHAR2(255);
ALTER TABLE AD_Process_Para MODIFY EntityType VARCHAR2(255);
ALTER TABLE AD_ReportView MODIFY EntityType VARCHAR2(255);
ALTER TABLE AD_Form MODIFY EntityType VARCHAR2(255);
ALTER TABLE AD_FieldGroup MODIFY EntityType VARCHAR2(255);
ALTER TABLE PA_MeasureCalc MODIFY EntityType VARCHAR2(255);
ALTER TABLE AD_Image MODIFY EntityType VARCHAR2(255);
ALTER TABLE AD_Workbench MODIFY EntityType VARCHAR2(255);
ALTER TABLE AD_WorkbenchWindow MODIFY EntityType VARCHAR2(255);
ALTER TABLE AD_ReplicationTable MODIFY EntityType VARCHAR2(255);
ALTER TABLE AD_ReplicationStrategy MODIFY EntityType VARCHAR2(255);
ALTER TABLE AD_WF_Node_Para MODIFY EntityType VARCHAR2(255);
ALTER TABLE AD_WF_Responsible MODIFY EntityType VARCHAR2(255);
ALTER TABLE AD_WF_NextCondition MODIFY EntityType VARCHAR2(255);
ALTER TABLE PA_ColorSchema MODIFY EntityType VARCHAR2(255);
ALTER TABLE AD_EntityType MODIFY EntityType VARCHAR2(255);
ALTER TABLE AD_Modification MODIFY EntityType VARCHAR2(255);
ALTER TABLE AD_InfoWindow MODIFY EntityType VARCHAR2(255);
ALTER TABLE AD_InfoColumn MODIFY EntityType VARCHAR2(255);
ALTER TABLE AD_SysConfig MODIFY EntityType VARCHAR2(255);
ALTER TABLE AD_ModelValidator MODIFY EntityType VARCHAR2(255);
ALTER TABLE PP_WF_Node_Product MODIFY EntityType VARCHAR2(255);
ALTER TABLE PP_Order_Node MODIFY EntityType VARCHAR2(255);
ALTER TABLE PP_Order_NodeNext MODIFY EntityType VARCHAR2(255);
ALTER TABLE PP_Order_Workflow MODIFY EntityType VARCHAR2(255);
ALTER TABLE AD_Rule MODIFY EntityType VARCHAR2(255);
ALTER TABLE AD_Migration MODIFY EntityType VARCHAR2(255);
ALTER TABLE AD_Browse_Field MODIFY EntityType VARCHAR2(255);
ALTER TABLE AD_Browse MODIFY EntityType VARCHAR2(255);
ALTER TABLE AD_View MODIFY EntityType VARCHAR2(255);
ALTER TABLE AD_View_Column MODIFY EntityType VARCHAR2(255);





/* Built with:
select t.TableName
	, 'INSERT INTO t_alter_column values('''||t.TableName||''',''EntityType'',''VARCHAR(255)'',null,null);' as sql_pg
	, 'ALTER TABLE '||t.tableName||' MODIFY EntityType VARCHAR2(255);' as sql_oracle
from AD_Column c
inner join AD_Table t on (t.AD_Table_ID=c.AD_Table_ID)
where c.AD_Element_ID=1682 and c.ColumnName='EntityType'
;
*/
