-- May 7, 2009 1:59:22 AM ECT
-- Advanced Search
CREATE TABLE C_CashFlow (AD_Client_ID NUMERIC(10) NOT NULL, AD_OrgTrx_ID NUMERIC(10) NOT NULL, AD_Org_ID NUMERIC(10) NOT NULL, C_BPartner_ID NUMERIC(10) NOT NULL, C_BankAccount_ID NUMERIC(10) DEFAULT NULL , C_CashFlow_ID NUMERIC(10) DEFAULT NULL , C_ConversionType_ID NUMERIC(10) DEFAULT NULL , C_Currency_ID NUMERIC(10) NOT NULL, C_PaymentTerm_ID NUMERIC(10) NOT NULL, Created TIMESTAMP NOT NULL, CreatedBy NUMERIC(10) NOT NULL, DateInvoiced TIMESTAMP NOT NULL, Description VARCHAR(255) DEFAULT NULL , DocumentNo VARCHAR(30) NOT NULL, DueDate TIMESTAMP DEFAULT NULL , GrandTotal NUMERIC DEFAULT NULL , IsActive CHAR(1) DEFAULT NULL CHECK (IsActive IN ('Y','N')), IsSOTrx CHAR(1) DEFAULT NULL CHECK (IsSOTrx IN ('Y','N')), Name VARCHAR(60) DEFAULT NULL , Updated TIMESTAMP NOT NULL, UpdatedBy NUMERIC(10) NOT NULL, CONSTRAINT C_CashFlow_Key PRIMARY KEY (C_CashFlow_ID))
;

