-- juddm BugFix:(Country Changes) 
-- add country Serbia
INSERT INTO C_COUNTRY
		(C_COUNTRY_ID, AD_CLIENT_ID, AD_ORG_ID, ISACTIVE, CREATED, CREATEDBY, UPDATED, UPDATEDBY,
		NAME, DESCRIPTION, COUNTRYCODE, HASREGION, DISPLAYSEQUENCE, HASPOSTAL_ADD, C_CURRENCY_ID,
		ISADDRESSLINESREVERSE, ISADDRESSLINESLOCALREVERSE)
	VALUES (349, 0, 0, 'Y', '2003-03-09 00:00:00.0', 0, '2000-01-02 00:00:00.0', 0,
		'Serbia', 'Serbia', 'RS', 'N', '@C@, @P@', 'N', 347, 'N', 'N');

-- add country Montenegro		
INSERT INTO C_COUNTRY
		(C_COUNTRY_ID, AD_CLIENT_ID, AD_ORG_ID, ISACTIVE, CREATED, CREATEDBY, UPDATED, UPDATEDBY,
		NAME, DESCRIPTION, COUNTRYCODE, HASREGION, DISPLAYSEQUENCE, HASPOSTAL_ADD, C_CURRENCY_ID,
		ISADDRESSLINESREVERSE, ISADDRESSLINESLOCALREVERSE)
	VALUES (350, 0, 0, 'Y', '2003-03-09 00:00:00.0', 0, '2000-01-02 00:00:00.0', 0,
		'Montenegro', 'Montenegro', 'ME', 'N', '@C@, @P@', 'N', 348, 'N', 'N');

-- deactivate Yugoslavia
UPDATE C_COUNTY SET ISACTIVE = 'N' WHERE C_COUNTRY_ID=346;

--add Serbian currency
INSERT INTO C_CURRENCY
			(C_CURRENCY_ID, AD_CLIENT_ID, AD_ORG_ID, ISACTIVE, CREATED, CREATEDBY, UPDATED, UPDATEDBY, ISO_CODE,
			CURSYMBOL, DESCRIPTION, STDPRECISION, COSTINGPRECISION, ISEURO, ISEMUMEMBER)
		VALUES(347, 0, 0, 'Y', '2003-08-06 17:05:45.0',0, '2000-01-02 00:00:00.0', 0, 'RSD',
			'RSD', 'Serbian Dinar', 2, 4, 'N', 'N')

-- add Montenegro currency
INSERT INTO C_CURRENCY
			(C_CURRENCY_ID, AD_CLIENT_ID, AD_ORG_ID, ISACTIVE, CREATED, CREATEDBY, UPDATED, UPDATEDBY, ISO_CODE,
			CURSYMBOL, DESCRIPTION, STDPRECISION, COSTINGPRECISION, ISEURO, ISEMUMEMBER)
		VALUES(348, 0, 0,'Y','2003-08-06 17:05:45.0', 0, '2000-01-02 00:00:00.0', 0,'MKD'
			'MKD', 'Denar',2,4,'N','N');

-- deactivate Yugoslavia currency
UPDATE C_CURRENCY SET ISACTIVE = 'N' WHERE C_CURRECNY_ID = 314;
