ALTER TABLE AD_MigrationStep DROP CONSTRAINT IF EXISTS ADMigration_ADMigrationStep;
ALTER TABLE AD_MigrationStep ADD CONSTRAINT ADMigration_ADMigrationStep FOREIGN KEY (AD_Migration_ID) REFERENCES AD_Migration
	ON DELETE CASCADE
	DEFERRABLE INITIALLY DEFERRED
;
	
ALTER TABLE AD_MigrationData DROP CONSTRAINT IF EXISTS ADMigrationStep_ADMigrationDat;
ALTER TABLE AD_MigrationData ADD CONSTRAINT ADMigrationStep_ADMigrationDat FOREIGN KEY (AD_MigrationStep_ID) REFERENCES AD_MigrationStep
	ON DELETE CASCADE
	DEFERRABLE INITIALLY DEFERRED
;
