ALTER TABLE AD_Browse ADD CONSTRAINT ADWindow_ADBrowse FOREIGN KEY (AD_Window_ID) REFERENCES AD_Window DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE AD_Browse_Field ADD CONSTRAINT ADValRule_ADBrowseField FOREIGN KEY (AD_Val_Rule_ID) REFERENCES AD_Val_Rule DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE AD_ChartDatasource ADD CONSTRAINT ADChart_ADChartDatasource FOREIGN KEY (AD_Chart_ID) REFERENCES AD_Chart DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE AD_ChartDatasource ADD CONSTRAINT EntityT_ADChartDatasource FOREIGN KEY (EntityType) REFERENCES AD_EntityType DEFERRABLE INITIALLY DEFERRED;  

ALTER TABLE AD_ChartDatasource ADD CONSTRAINT ADTable_ADChartDatasource FOREIGN KEY (AD_Table_ID) REFERENCES AD_Table DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE AD_Column ADD CONSTRAINT ADChart_ADColumn FOREIGN KEY (AD_Chart_ID) REFERENCES AD_Chart DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE AD_Memo ADD CONSTRAINT ADTable_ADMemo FOREIGN KEY (AD_Table_ID) REFERENCES AD_Table DEFERRABLE INITIALLY DEFERRED; 

ALTER TABLE AD_Memo ADD CONSTRAINT ADUser_ADMemo FOREIGN KEY (AD_User_ID) REFERENCES AD_User DEFERRABLE INITIALLY DEFERRED; 

ALTER TABLE AD_Memo ADD CONSTRAINT CActivity_ADMemo FOREIGN KEY (C_Activity_ID) REFERENCES C_Activity DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE AD_Memo ADD CONSTRAINT CBPartner_ADMemo FOREIGN KEY (C_BPartner_ID) REFERENCES C_BPartner DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE AD_Memo ADD CONSTRAINT CCampaign_ADMemo FOREIGN KEY (C_Campaign_ID) REFERENCES C_Campaign DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE AD_Memo ADD CONSTRAINT CProject_ADMemo FOREIGN KEY (C_Project_ID) REFERENCES C_Project DEFERRABLE INITIALLY DEFERRED; 

ALTER TABLE AD_Memo ADD CONSTRAINT MProduct_ADMemo FOREIGN KEY (M_Product_ID) REFERENCES M_Product DEFERRABLE INITIALLY DEFERRED; 

ALTER TABLE AD_Migration ADD CONSTRAINT EntityT_ADMigration FOREIGN KEY (EntityType) REFERENCES AD_EntityType DEFERRABLE INITIALLY DEFERRED; 

ALTER TABLE AD_MigrationData ADD CONSTRAINT ADColumn_ADMigrationData FOREIGN KEY (AD_Column_ID) REFERENCES AD_Column DEFERRABLE INITIALLY DEFERRED; 

ALTER TABLE AD_MigrationData ADD CONSTRAINT ADMigrationStep_ADMigrationDat FOREIGN KEY (AD_MigrationStep_ID) REFERENCES AD_MigrationStep DEFERRABLE INITIALLY DEFERRED; 

ALTER TABLE AD_MigrationStep ADD CONSTRAINT ADMigration_ADMigrationStep FOREIGN KEY (AD_Migration_ID) REFERENCES AD_Migration DEFERRABLE INITIALLY DEFERRED; 

ALTER TABLE AD_MigrationStep ADD CONSTRAINT ADTable_ADMigrationStep FOREIGN KEY (AD_Table_ID) REFERENCES AD_Table DEFERRABLE INITIALLY DEFERRED;  

ALTER TABLE AD_Scheduler ADD CONSTRAINT ADTable_ADScheduler FOREIGN KEY (AD_Table_ID) REFERENCES AD_Table DEFERRABLE INITIALLY DEFERRED;  

ALTER TABLE AD_Table_Process ADD CONSTRAINT EntityT_ADTableProcess FOREIGN KEY (EntityType) REFERENCES AD_EntityType DEFERRABLE INITIALLY DEFERRED; 

ALTER TABLE AD_User ADD CONSTRAINT SalesRep_ADUser FOREIGN KEY (SalesRep_ID) REFERENCES AD_User DEFERRABLE INITIALLY DEFERRED; 

ALTER TABLE AD_User ADD CONSTRAINT CCampaign_ADUser FOREIGN KEY (C_Campaign_ID) REFERENCES C_Campaign DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE C_AllocationLine ADD CONSTRAINT CCharge_CAllocationLine FOREIGN KEY (C_Charge_ID) REFERENCES C_Charge DEFERRABLE INITIALLY DEFERRED;  

ALTER TABLE C_BPartner_Location ADD CONSTRAINT HRRelationship_CBPartnerLocati FOREIGN KEY (HR_Relationship_ID) REFERENCES HR_Relationship DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE C_CashFlow ADD CONSTRAINT ADOrgTrx_CCashFlow FOREIGN KEY (AD_OrgTrx_ID) REFERENCES AD_Org DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE C_CashFlow ADD CONSTRAINT CBankAccount_CCashFlow FOREIGN KEY (C_BankAccount_ID) REFERENCES C_BankAccount DEFERRABLE INITIALLY DEFERRED; 

ALTER TABLE C_CashFlow ADD CONSTRAINT CBPartner_CCashFlow FOREIGN KEY (C_BPartner_ID) REFERENCES C_BPartner DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE C_CashFlow ADD CONSTRAINT CConversionType_CCashFlow FOREIGN KEY (C_ConversionType_ID) REFERENCES C_ConversionType DEFERRABLE INITIALLY DEFERRED; 

ALTER TABLE C_CashFlow ADD CONSTRAINT CCurrency_CCashFlow FOREIGN KEY (C_Currency_ID) REFERENCES C_Currency DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE C_CashFlow ADD CONSTRAINT CPaymentTerm_CCashFlow FOREIGN KEY (C_PaymentTerm_ID) REFERENCES C_PaymentTerm DEFERRABLE INITIALLY DEFERRED; 

ALTER TABLE C_ContactActivity ADD CONSTRAINT ADUser_CContactActivity FOREIGN KEY (AD_User_ID) REFERENCES AD_User DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE C_ContactActivity ADD CONSTRAINT SalesRep_CContactActivity FOREIGN KEY (SalesRep_ID) REFERENCES AD_User DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE C_ContactActivity ADD CONSTRAINT COpportunity_CContactActivity FOREIGN KEY (C_Opportunity_ID) REFERENCES C_Opportunity DEFERRABLE INITIALLY DEFERRED; 

ALTER TABLE C_LandedCostAllocation ADD CONSTRAINT MInOutLine_CLandedCostAllocati FOREIGN KEY (M_InOutLine_ID) REFERENCES M_InOutLine DEFERRABLE INITIALLY DEFERRED;  

ALTER TABLE C_Opportunity ADD CONSTRAINT ADUser_COpportunity FOREIGN KEY (AD_User_ID) REFERENCES AD_User DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE C_Opportunity ADD CONSTRAINT SalesRep_COpportunity FOREIGN KEY (SalesRep_ID) REFERENCES AD_User DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE C_Opportunity ADD CONSTRAINT CBPartner_COpportunity FOREIGN KEY (C_BPartner_ID) REFERENCES C_BPartner DEFERRABLE INITIALLY DEFERRED;  

ALTER TABLE C_Opportunity ADD CONSTRAINT CCampaign_COpportunity FOREIGN KEY (C_Campaign_ID) REFERENCES C_Campaign DEFERRABLE INITIALLY DEFERRED;  

ALTER TABLE C_Opportunity ADD CONSTRAINT CCurrency_COpportunity FOREIGN KEY (C_Currency_ID) REFERENCES C_Currency DEFERRABLE INITIALLY DEFERRED;  

ALTER TABLE C_Opportunity ADD CONSTRAINT COrder_COpportunity FOREIGN KEY (C_Order_ID) REFERENCES C_Order DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE C_Opportunity ADD CONSTRAINT CSalesStage_COpportunity FOREIGN KEY (C_SalesStage_ID) REFERENCES C_SalesStage DEFERRABLE INITIALLY DEFERRED; 

ALTER TABLE C_Order ADD CONSTRAINT COpportunity_COrder FOREIGN KEY (C_Opportunity_ID) REFERENCES C_Opportunity DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE DD_OrderLine ADD CONSTRAINT MShipper_DDOrderLine FOREIGN KEY (M_Shipper_ID) REFERENCES M_Shipper DEFERRABLE INITIALLY DEFERRED;  

ALTER TABLE DD_OrderLine ADD CONSTRAINT WMInOutBoundLine_DDOrderLine FOREIGN KEY (WM_InOutBoundLine_ID) REFERENCES WM_InOutBoundLine DEFERRABLE INITIALLY DEFERRED;  

ALTER TABLE Fact_Acct_Summary ADD CONSTRAINT ADOrgTrx_FactAcctSummary FOREIGN KEY (AD_OrgTrx_ID) REFERENCES AD_Org DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE Fact_Acct_Summary ADD CONSTRAINT CLocFrom_FactAcctSummary FOREIGN KEY (C_LocFrom_ID) REFERENCES C_Location DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE Fact_Acct_Summary ADD CONSTRAINT CLocTo_FactAcctSummary FOREIGN KEY (C_LocTo_ID) REFERENCES C_Location DEFERRABLE INITIALLY DEFERRED; 

ALTER TABLE Fact_Reconciliation ADD CONSTRAINT FactAcct_FactReconciliation FOREIGN KEY (Fact_Acct_ID) REFERENCES Fact_Acct DEFERRABLE INITIALLY DEFERRED; 

ALTER TABLE GL_JournalLine ADD CONSTRAINT ADOrgTrx_GLJournalLine FOREIGN KEY (AD_OrgTrx_ID) REFERENCES AD_Org DEFERRABLE INITIALLY DEFERRED; 

ALTER TABLE GL_JournalLine ADD CONSTRAINT CActivity_GLJournalLine FOREIGN KEY (C_Activity_ID) REFERENCES C_Activity DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE GL_JournalLine ADD CONSTRAINT CBPartner_GLJournalLine FOREIGN KEY (C_BPartner_ID) REFERENCES C_BPartner DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE GL_JournalLine ADD CONSTRAINT CCampaign_GLJournalLine FOREIGN KEY (C_Campaign_ID) REFERENCES C_Campaign DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE GL_JournalLine ADD CONSTRAINT Account_GLJournalLine FOREIGN KEY (Account_ID) REFERENCES C_ElementValue DEFERRABLE INITIALLY DEFERRED; 

ALTER TABLE GL_JournalLine ADD CONSTRAINT User1_GLJournalLine FOREIGN KEY (User1_ID) REFERENCES C_ElementValue DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE GL_JournalLine ADD CONSTRAINT User2_GLJournalLine FOREIGN KEY (User2_ID) REFERENCES C_ElementValue DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE GL_JournalLine ADD CONSTRAINT CLocFrom_GLJournalLine FOREIGN KEY (C_LocFrom_ID) REFERENCES C_Location DEFERRABLE INITIALLY DEFERRED;  

ALTER TABLE GL_JournalLine ADD CONSTRAINT CLocTo_GLJournalLine FOREIGN KEY (C_LocTo_ID) REFERENCES C_Location DEFERRABLE INITIALLY DEFERRED; 

ALTER TABLE GL_JournalLine ADD CONSTRAINT CProject_GLJournalLine FOREIGN KEY (C_Project_ID) REFERENCES C_Project DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE GL_JournalLine ADD CONSTRAINT CSalesRegion_GLJournalLine FOREIGN KEY (C_SalesRegion_ID) REFERENCES C_SalesRegion DEFERRABLE INITIALLY DEFERRED;  

ALTER TABLE GL_JournalLine ADD CONSTRAINT CSubAcct_GLJournalLine FOREIGN KEY (C_SubAcct_ID) REFERENCES C_SubAcct DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE GL_JournalLine ADD CONSTRAINT AliasValidCombination_GLJourna FOREIGN KEY (Alias_ValidCombination_ID) REFERENCES C_ValidCombination DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE GL_JournalLine ADD CONSTRAINT MProduct_GLJournalLine FOREIGN KEY (M_Product_ID) REFERENCES M_Product DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE GL_JournalLine ADD CONSTRAINT UserElement1_GLJournalLine FOREIGN KEY (UserElement1_ID) REFERENCES C_ElementValue DEFERRABLE INITIALLY DEFERRED; 

ALTER TABLE GL_JournalLine ADD CONSTRAINT UserElement2_GLJournalLine FOREIGN KEY (UserElement2_ID) REFERENCES C_ElementValue DEFERRABLE INITIALLY DEFERRED; 

ALTER TABLE HR_Attribute ADD CONSTRAINT CCharge_HRAttribute FOREIGN KEY (C_Charge_ID) REFERENCES C_Charge DEFERRABLE INITIALLY DEFERRED;  

ALTER TABLE HR_Attribute ADD CONSTRAINT CDocType_HRAttribute FOREIGN KEY (C_DocType_ID) REFERENCES C_DocType DEFERRABLE INITIALLY DEFERRED;  

ALTER TABLE HR_Attribute ADD CONSTRAINT CInvoice_HRAttribute FOREIGN KEY (C_Invoice_ID) REFERENCES C_Invoice DEFERRABLE INITIALLY DEFERRED;  

ALTER TABLE HR_Department ADD CONSTRAINT CBPartner_HRDepartment FOREIGN KEY (C_BPartner_ID) REFERENCES C_BPartner DEFERRABLE INITIALLY DEFERRED;  

ALTER TABLE HR_DepartmentProduct ADD CONSTRAINT HRDepartment_HRDepartmentProdu FOREIGN KEY (HR_Department_ID) REFERENCES HR_Department DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE HR_DepartmentProduct ADD CONSTRAINT MProduct_HRDepartmentProduct FOREIGN KEY (M_Product_ID) REFERENCES M_Product DEFERRABLE INITIALLY DEFERRED;  

ALTER TABLE HR_Designation ADD CONSTRAINT HREmployeeType_HRDesignation FOREIGN KEY (HR_EmployeeType_ID) REFERENCES HR_EmployeeType DEFERRABLE INITIALLY DEFERRED; 

ALTER TABLE HR_Designation ADD CONSTRAINT HRPayroll_HRDesignation FOREIGN KEY (HR_Payroll_ID) REFERENCES HR_Payroll DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE HR_Designation ADD CONSTRAINT HRSalaryStructure_HRDesignatio FOREIGN KEY (HR_SalaryStructure_ID) REFERENCES HR_SalaryStructure DEFERRABLE INITIALLY DEFERRED; 

ALTER TABLE HR_Education ADD CONSTRAINT HRDegree_HREducation FOREIGN KEY (HR_Degree_ID) REFERENCES HR_Degree DEFERRABLE INITIALLY DEFERRED;  

ALTER TABLE HR_Education ADD CONSTRAINT HREmployee_HREducation FOREIGN KEY (HR_Employee_ID) REFERENCES HR_Employee DEFERRABLE INITIALLY DEFERRED; 

ALTER TABLE HR_Employee ADD CONSTRAINT ADUser_HREmployee FOREIGN KEY (AD_User_ID) REFERENCES AD_User DEFERRABLE INITIALLY DEFERRED; 

ALTER TABLE HR_Employee ADD CONSTRAINT Nationality_HREmployee FOREIGN KEY (Nationality_ID) REFERENCES C_Country DEFERRABLE INITIALLY DEFERRED; 

ALTER TABLE HR_Employee ADD CONSTRAINT HREmployeeType_HREmployee FOREIGN KEY (HR_EmployeeType_ID) REFERENCES HR_EmployeeType DEFERRABLE INITIALLY DEFERRED;  

ALTER TABLE HR_Employee ADD CONSTRAINT HRRace_HREmployee FOREIGN KEY (HR_Race_ID) REFERENCES HR_Race DEFERRABLE INITIALLY DEFERRED; 

ALTER TABLE HR_Employee ADD CONSTRAINT HRSkillType_HREmployee FOREIGN KEY (HR_SkillType_ID) REFERENCES HR_SkillType DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE HR_EmployeeDependent ADD CONSTRAINT HREmployee_HREmployeeDependent FOREIGN KEY (HR_Employee_ID) REFERENCES HR_Employee DEFERRABLE INITIALLY DEFERRED; 

ALTER TABLE HR_EmployeeDependent ADD CONSTRAINT HRRelationship_HREmployeeDepen FOREIGN KEY (HR_Relationship_ID) REFERENCES HR_Relationship DEFERRABLE INITIALLY DEFERRED; 

ALTER TABLE HR_EmployeeExperience ADD CONSTRAINT HREmployee_HREmployeeExperienc FOREIGN KEY (HR_Employee_ID) REFERENCES HR_Employee DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE HR_EmployeeInsurance ADD CONSTRAINT HREmployee_HREmployeeInsurance FOREIGN KEY (HR_Employee_ID) REFERENCES HR_Employee DEFERRABLE INITIALLY DEFERRED; 

ALTER TABLE HR_EmployeeInsurance ADD CONSTRAINT HRInsuranceType_HREmployeeInsu FOREIGN KEY (HR_InsuranceType_ID) REFERENCES HR_InsuranceType DEFERRABLE INITIALLY DEFERRED;  

ALTER TABLE HR_EmployeeInsurance ADD CONSTRAINT HRPeriod_HREmployeeInsurance FOREIGN KEY (HR_Period_ID) REFERENCES HR_Period DEFERRABLE INITIALLY DEFERRED;  

ALTER TABLE HR_EmployeeType ADD CONSTRAINT HRPayroll_HREmployeeType FOREIGN KEY (HR_Payroll_ID) REFERENCES HR_Payroll DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE HR_EmployeeWeeklyOff ADD CONSTRAINT HREmployee_HREmployeeWeeklyOff FOREIGN KEY (HR_Employee_ID) REFERENCES HR_Employee DEFERRABLE INITIALLY DEFERRED; 

ALTER TABLE HR_Interview ADD CONSTRAINT CBPartner_HRInterview FOREIGN KEY (C_BPartner_ID) REFERENCES C_BPartner DEFERRABLE INITIALLY DEFERRED; 

ALTER TABLE HR_Interview ADD CONSTRAINT HRJobApplication_HRInterview FOREIGN KEY (HR_JobApplication_ID) REFERENCES HR_JobApplication DEFERRABLE INITIALLY DEFERRED;  

ALTER TABLE HR_JobApplication ADD CONSTRAINT CBPartner_HRJobApplication FOREIGN KEY (C_BPartner_ID) REFERENCES C_BPartner DEFERRABLE INITIALLY DEFERRED;  

ALTER TABLE HR_JobApplication ADD CONSTRAINT RecruitedEmployee_HRJobApplica FOREIGN KEY (RecruitedEmployee_ID) REFERENCES C_BPartner DEFERRABLE INITIALLY DEFERRED;  

ALTER TABLE HR_JobApplication ADD CONSTRAINT RefBPartner_HRJobApplication FOREIGN KEY (Ref_BPartner_ID) REFERENCES C_BPartner DEFERRABLE INITIALLY DEFERRED; 

ALTER TABLE HR_JobApplication ADD CONSTRAINT HRDesignation_HRJobApplication FOREIGN KEY (HR_Designation_ID) REFERENCES HR_Designation DEFERRABLE INITIALLY DEFERRED; 

ALTER TABLE HR_JobApplication ADD CONSTRAINT HRJobOpening_HRJobApplication FOREIGN KEY (HR_JobOpening_ID) REFERENCES HR_JobOpening DEFERRABLE INITIALLY DEFERRED; 

ALTER TABLE HR_JobApplicationHistory ADD CONSTRAINT HRJobApplication_HRJobApplicat FOREIGN KEY (HR_JobApplication_ID) REFERENCES HR_JobApplication DEFERRABLE INITIALLY DEFERRED; 

ALTER TABLE HR_JobOpening ADD CONSTRAINT ADUser_HRJobOpening FOREIGN KEY (AD_User_ID) REFERENCES AD_User DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE HR_JobOpening ADD CONSTRAINT Supervisor_HRJobOpening FOREIGN KEY (Supervisor_ID) REFERENCES AD_User DEFERRABLE INITIALLY DEFERRED; 

ALTER TABLE HR_JobOpening ADD CONSTRAINT CDocType_HRJobOpening FOREIGN KEY (C_DocType_ID) REFERENCES C_DocType DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE HR_JobOpening ADD CONSTRAINT HRCareerLevel_HRJobOpening FOREIGN KEY (HR_CareerLevel_ID) REFERENCES HR_CareerLevel DEFERRABLE INITIALLY DEFERRED; 

ALTER TABLE HR_JobOpening ADD CONSTRAINT HRDepartment_HRJobOpening FOREIGN KEY (HR_Department_ID) REFERENCES HR_Department DEFERRABLE INITIALLY DEFERRED; 

ALTER TABLE HR_JobOpening ADD CONSTRAINT HRDesignation_HRJobOpening FOREIGN KEY (HR_Designation_ID) REFERENCES HR_Designation DEFERRABLE INITIALLY DEFERRED; 

ALTER TABLE HR_JobOpening ADD CONSTRAINT HRJobEducation_HRJobOpening FOREIGN KEY (HR_JobEducation_ID) REFERENCES HR_JobEducation DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE HR_JobOpening ADD CONSTRAINT HRJobOpening_HRJobOpening FOREIGN KEY (HR_JobOpening_ID) REFERENCES HR_JobOpening DEFERRABLE INITIALLY DEFERRED; 

ALTER TABLE HR_JobOpening ADD CONSTRAINT HRJobType_HRJobOpening FOREIGN KEY (HR_JobType_ID) REFERENCES HR_JobType DEFERRABLE INITIALLY DEFERRED;  

ALTER TABLE HR_JobOpening ADD CONSTRAINT HRSalaryRange_HRJobOpening FOREIGN KEY (HR_SalaryRange_ID) REFERENCES HR_SalaryRange DEFERRABLE INITIALLY DEFERRED; 

ALTER TABLE HR_JobOpeningHistory ADD CONSTRAINT ADUser_HRJobOpeningHistory FOREIGN KEY (AD_User_ID) REFERENCES AD_User DEFERRABLE INITIALLY DEFERRED;  

ALTER TABLE HR_JobOpeningHistory ADD CONSTRAINT HRJobOpening_HRJobOpeningHisto FOREIGN KEY (HR_JobOpening_ID) REFERENCES HR_JobOpening DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE HR_LeaveAssign ADD CONSTRAINT CYear_HRLeaveAssign FOREIGN KEY (C_Year_ID) REFERENCES C_Year DEFERRABLE INITIALLY DEFERRED; 

ALTER TABLE HR_LeaveAssign ADD CONSTRAINT HREmployee_HRLeaveAssign FOREIGN KEY (HR_Employee_ID) REFERENCES HR_Employee DEFERRABLE INITIALLY DEFERRED;  

ALTER TABLE HR_LeaveAssign ADD CONSTRAINT HRLeaveType_HRLeaveAssign FOREIGN KEY (HR_LeaveType_ID) REFERENCES HR_LeaveType DEFERRABLE INITIALLY DEFERRED;  

ALTER TABLE HR_LeaveCreditHistory ADD CONSTRAINT CYear_HRLeaveCreditHistory FOREIGN KEY (C_Year_ID) REFERENCES C_Year DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE HR_LeaveCreditHistory ADD CONSTRAINT HREmployee_HRLeaveCreditHistor FOREIGN KEY (HR_Employee_ID) REFERENCES HR_Employee DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE HR_LeaveCreditHistory ADD CONSTRAINT HRLeaveAssign_HRLeaveCreditHis FOREIGN KEY (HR_LeaveAssign_ID) REFERENCES HR_LeaveAssign DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE HR_LeaveCreditHistory ADD CONSTRAINT HRLeaveReason_HRLeaveCreditHis FOREIGN KEY (HR_LeaveReason_ID) REFERENCES HR_LeaveReason DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE HR_LeaveCreditHistory ADD CONSTRAINT HRLeaveType_HRLeaveCreditHisto FOREIGN KEY (HR_LeaveType_ID) REFERENCES HR_LeaveType DEFERRABLE INITIALLY DEFERRED; 

ALTER TABLE HR_LeaveTypeCombination ADD CONSTRAINT AllowedLeaveType_HRLeaveTypeCo FOREIGN KEY (AllowedLeaveType_ID) REFERENCES HR_LeaveType DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE HR_LeaveTypeCombination ADD CONSTRAINT HRLeaveType_HRLeaveTypeCombina FOREIGN KEY (HR_LeaveType_ID) REFERENCES HR_LeaveType DEFERRABLE INITIALLY DEFERRED;  

ALTER TABLE HR_LeaveTypeEmployeeType ADD CONSTRAINT HREmployeeType_HRLeaveTypeEmpl FOREIGN KEY (HR_EmployeeType_ID) REFERENCES HR_EmployeeType DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE HR_LeaveTypeEmployeeType ADD CONSTRAINT HRLeaveType_HRLeaveTypeEmploye FOREIGN KEY (HR_LeaveType_ID) REFERENCES HR_LeaveType DEFERRABLE INITIALLY DEFERRED; 

ALTER TABLE HR_Movement ADD CONSTRAINT CBPBankAccount_HRMovement FOREIGN KEY (C_BP_BankAccount_ID) REFERENCES C_BP_BankAccount DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE HR_Movement ADD CONSTRAINT CBPGroup_HRMovement FOREIGN KEY (C_BP_Group_ID) REFERENCES C_BP_Group DEFERRABLE INITIALLY DEFERRED;  

ALTER TABLE HR_PaySelection ADD CONSTRAINT CBankAccount_HRPaySelection FOREIGN KEY (C_BankAccount_ID) REFERENCES C_BankAccount DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE HR_PaySelectionCheck ADD CONSTRAINT CBPartner_HRPaySelectionCheck FOREIGN KEY (C_BPartner_ID) REFERENCES C_BPartner DEFERRABLE INITIALLY DEFERRED; 

ALTER TABLE HR_PaySelectionCheck ADD CONSTRAINT CBPBankAccount_HRPaySelectionC FOREIGN KEY (C_BP_BankAccount_ID) REFERENCES C_BP_BankAccount DEFERRABLE INITIALLY DEFERRED;  

ALTER TABLE HR_PaySelectionCheck ADD CONSTRAINT CPayment_HRPaySelectionCheck FOREIGN KEY (C_Payment_ID) REFERENCES C_Payment DEFERRABLE INITIALLY DEFERRED;  

ALTER TABLE HR_PaySelectionCheck ADD CONSTRAINT HRPaySelection_HRPaySelectionC FOREIGN KEY (HR_PaySelection_ID) REFERENCES HR_PaySelection DEFERRABLE INITIALLY DEFERRED; 

ALTER TABLE HR_PaySelectionLine ADD CONSTRAINT HRMovement_HRPaySelectionLine FOREIGN KEY (HR_Movement_ID) REFERENCES HR_Movement DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE HR_PaySelectionLine ADD CONSTRAINT HRPaySelection_HRPaySelectionL FOREIGN KEY (HR_PaySelection_ID) REFERENCES HR_PaySelection DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE HR_PaySelectionLine ADD CONSTRAINT HRPaySelectionCheck_HRPaySelec FOREIGN KEY (HR_PaySelectionCheck_ID) REFERENCES HR_PaySelectionCheck DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE HR_SalaryStructure ADD CONSTRAINT HRSalaryStructure_HRSalaryStru FOREIGN KEY (HR_SalaryStructure_ID) REFERENCES HR_SalaryStructure DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE HR_SalaryStructureLine ADD CONSTRAINT HRConcept_HRSalaryStructureLin FOREIGN KEY (HR_Concept_ID) REFERENCES HR_Concept DEFERRABLE INITIALLY DEFERRED; 

ALTER TABLE HR_SalaryStructureLine ADD CONSTRAINT HRSalStruc_HRSalStrucLine FOREIGN KEY (HR_SalaryStructure_ID) REFERENCES HR_SalaryStructure DEFERRABLE INITIALLY DEFERRED; 

ALTER TABLE HR_ShiftGroup ADD CONSTRAINT HRShiftGroup_HRShiftGroup FOREIGN KEY (HR_ShiftGroup_ID) REFERENCES HR_ShiftGroup DEFERRABLE INITIALLY DEFERRED; 

ALTER TABLE HR_WorkGroup ADD CONSTRAINT HRShiftGroup_HRWorkGroup FOREIGN KEY (HR_ShiftGroup_ID) REFERENCES HR_ShiftGroup DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE HR_WorkGroup ADD CONSTRAINT HRWorkShift_HRWorkGroup FOREIGN KEY (HR_WorkShift_ID) REFERENCES HR_WorkShift DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE HR_WorkShift ADD CONSTRAINT HRShiftGroup_HRWorkShift FOREIGN KEY (HR_ShiftGroup_ID) REFERENCES HR_ShiftGroup DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE I_ElementValue ADD CONSTRAINT CCharge_IElementValue FOREIGN KEY (C_Charge_ID) REFERENCES C_Charge DEFERRABLE INITIALLY DEFERRED; 

ALTER TABLE I_ElementValue ADD CONSTRAINT CTaxCategory_IElementValue FOREIGN KEY (C_TaxCategory_ID) REFERENCES C_TaxCategory DEFERRABLE INITIALLY DEFERRED;  

ALTER TABLE I_HR_Movement ADD CONSTRAINT CBPartner_IHRMovement FOREIGN KEY (C_BPartner_ID) REFERENCES C_BPartner DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE I_HR_Movement ADD CONSTRAINT HRConcept_IHRMovement FOREIGN KEY (HR_Concept_ID) REFERENCES HR_Concept DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE I_HR_Movement ADD CONSTRAINT HRMovement_IHRMovement FOREIGN KEY (HR_Movement_ID) REFERENCES HR_Movement DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE I_HR_Movement ADD CONSTRAINT HRProcess_IHRMovement FOREIGN KEY (HR_Process_ID) REFERENCES HR_Process DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE I_Invoice ADD CONSTRAINT CDunningLevel_IInvoice FOREIGN KEY (C_DunningLevel_ID) REFERENCES C_DunningLevel DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE I_Movement ADD CONSTRAINT ADOrgTrx_IMovement FOREIGN KEY (AD_OrgTrx_ID) REFERENCES AD_Org DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE I_Movement ADD CONSTRAINT ADUser_IMovement FOREIGN KEY (AD_User_ID) REFERENCES AD_User DEFERRABLE INITIALLY DEFERRED; 

ALTER TABLE I_Movement ADD CONSTRAINT CBPartner_IMovement FOREIGN KEY (C_BPartner_ID) REFERENCES C_BPartner DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE I_Movement ADD CONSTRAINT CCampaign_IMovement FOREIGN KEY (C_Campaign_ID) REFERENCES C_Campaign DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE I_Movement ADD CONSTRAINT CDocType_IMovement FOREIGN KEY (C_DocType_ID) REFERENCES C_DocType DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE I_Movement ADD CONSTRAINT CProject_IMovement FOREIGN KEY (C_Project_ID) REFERENCES C_Project DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE I_Movement ADD CONSTRAINT MMovement_IMovement FOREIGN KEY (M_Movement_ID) REFERENCES M_Movement DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE I_Movement ADD CONSTRAINT MMovementLine_IMovement FOREIGN KEY (M_MovementLine_ID) REFERENCES M_MovementLine DEFERRABLE INITIALLY DEFERRED; 

ALTER TABLE I_Movement ADD CONSTRAINT MProduct_IMovement FOREIGN KEY (M_Product_ID) REFERENCES M_Product DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE I_Movement ADD CONSTRAINT MShipper_IMovement FOREIGN KEY (M_Shipper_ID) REFERENCES M_Shipper DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE I_Product_ASI ADD CONSTRAINT MAttribute_IProductASI FOREIGN KEY (M_Attribute_ID) REFERENCES M_Attribute DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE I_Product_ASI ADD CONSTRAINT MAttributeSearch_IProductASI FOREIGN KEY (M_AttributeSearch_ID) REFERENCES M_AttributeSearch DEFERRABLE INITIALLY DEFERRED; 

ALTER TABLE I_Product_ASI ADD CONSTRAINT MAttributeSet_IProductASI FOREIGN KEY (M_AttributeSet_ID) REFERENCES M_AttributeSet DEFERRABLE INITIALLY DEFERRED;  

ALTER TABLE I_Product_ASI ADD CONSTRAINT MAttributeValue_IProductASI FOREIGN KEY (M_AttributeValue_ID) REFERENCES M_AttributeValue DEFERRABLE INITIALLY DEFERRED; 

ALTER TABLE I_Product_ASI ADD CONSTRAINT MProduct_IProductASI FOREIGN KEY (M_Product_ID) REFERENCES M_Product DEFERRABLE INITIALLY DEFERRED; 

ALTER TABLE I_Product_BOM ADD CONSTRAINT CUOM_IProductBOM FOREIGN KEY (C_UOM_ID) REFERENCES C_UOM DEFERRABLE INITIALLY DEFERRED;  

ALTER TABLE I_Product_BOM ADD CONSTRAINT MChangeNotice_IProductBOM FOREIGN KEY (M_ChangeNotice_ID) REFERENCES M_ChangeNotice DEFERRABLE INITIALLY DEFERRED;  

ALTER TABLE I_Product_BOM ADD CONSTRAINT MBOMProduct_IProductBOM FOREIGN KEY (M_BOMProduct_ID) REFERENCES M_Product DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE I_Product_BOM ADD CONSTRAINT MProduct_IProductBOM FOREIGN KEY (M_Product_ID) REFERENCES M_Product DEFERRABLE INITIALLY DEFERRED; 

ALTER TABLE I_Product_BOM ADD CONSTRAINT PPProductBOM_IProductBOM FOREIGN KEY (PP_Product_BOM_ID) REFERENCES PP_Product_BOM DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE I_Product_BOM ADD CONSTRAINT PPProductBOMLine_IProductBOM FOREIGN KEY (PP_Product_BOMLine_ID) REFERENCES PP_Product_BOMLine DEFERRABLE INITIALLY DEFERRED;  

ALTER TABLE I_Workflow ADD CONSTRAINT ADColumn_IWorkflow FOREIGN KEY (AD_Column_ID) REFERENCES AD_Column DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE I_Workflow ADD CONSTRAINT EntityT_IWorkflow FOREIGN KEY (EntityType) REFERENCES AD_EntityType DEFERRABLE INITIALLY DEFERRED;  

ALTER TABLE I_Workflow ADD CONSTRAINT ADForm_IWorkflow FOREIGN KEY (AD_Form_ID) REFERENCES AD_Form DEFERRABLE INITIALLY DEFERRED; 

ALTER TABLE I_Workflow ADD CONSTRAINT ADImage_IWorkflow FOREIGN KEY (AD_Image_ID) REFERENCES AD_Image DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE I_Workflow ADD CONSTRAINT ADProcess_IWorkflow FOREIGN KEY (AD_Process_ID) REFERENCES AD_Process DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE I_Workflow ADD CONSTRAINT ADTable_IWorkflow FOREIGN KEY (AD_Table_ID) REFERENCES AD_Table DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE I_Workflow ADD CONSTRAINT ADTask_IWorkflow FOREIGN KEY (AD_Task_ID) REFERENCES AD_Task DEFERRABLE INITIALLY DEFERRED; 

ALTER TABLE I_Workflow ADD CONSTRAINT ADWFNode_IWorkflow FOREIGN KEY (AD_WF_Node_ID) REFERENCES AD_WF_Node DEFERRABLE INITIALLY DEFERRED; 

ALTER TABLE I_Workflow ADD CONSTRAINT ADWFResponsible_IWorkflow FOREIGN KEY (AD_WF_Responsible_ID) REFERENCES AD_WF_Responsible DEFERRABLE INITIALLY DEFERRED; 

ALTER TABLE I_Workflow ADD CONSTRAINT ADWindow_IWorkflow FOREIGN KEY (AD_Window_ID) REFERENCES AD_Window DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE I_Workflow ADD CONSTRAINT ADWorkflow_IWorkflow FOREIGN KEY (AD_Workflow_ID) REFERENCES AD_Workflow DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE I_Workflow ADD CONSTRAINT ADWorkflowProcessor_IWorkflow FOREIGN KEY (AD_WorkflowProcessor_ID) REFERENCES AD_WorkflowProcessor DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE I_Workflow ADD CONSTRAINT RMailText_IWorkflow FOREIGN KEY (R_MailText_ID) REFERENCES R_MailText DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE I_Workflow ADD CONSTRAINT SResource_IWorkflow FOREIGN KEY (S_Resource_ID) REFERENCES S_Resource DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE M_BP_Price ADD CONSTRAINT CBPartner_MBPPrice FOREIGN KEY (C_BPartner_ID) REFERENCES C_BPartner DEFERRABLE INITIALLY DEFERRED; 

ALTER TABLE M_BP_Price ADD CONSTRAINT CCurrency_MBPPrice FOREIGN KEY (C_Currency_ID) REFERENCES C_Currency DEFERRABLE INITIALLY DEFERRED; 

ALTER TABLE M_BP_Price ADD CONSTRAINT MProduct_MBPPrice FOREIGN KEY (M_Product_ID) REFERENCES M_Product DEFERRABLE INITIALLY DEFERRED; 

ALTER TABLE M_Cost ADD CONSTRAINT MWarehouse_MCost FOREIGN KEY (M_Warehouse_ID) REFERENCES M_Warehouse DEFERRABLE INITIALLY DEFERRED;  

ALTER TABLE M_CostDetail ADD CONSTRAINT CLandedCostAllocation_MCostDet FOREIGN KEY (C_LandedCostAllocation_ID) REFERENCES C_LandedCostAllocation DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE M_CostDetail ADD CONSTRAINT MCostType_MCostDetail FOREIGN KEY (M_CostType_ID) REFERENCES M_CostType DEFERRABLE INITIALLY DEFERRED; 

ALTER TABLE M_CostDetail ADD CONSTRAINT MWarehouse_MCostDetail FOREIGN KEY (M_Warehouse_ID) REFERENCES M_Warehouse DEFERRABLE INITIALLY DEFERRED; 

ALTER TABLE M_Product ADD CONSTRAINT MPartType_MProduct FOREIGN KEY (M_PartType_ID) REFERENCES M_PartType DEFERRABLE INITIALLY DEFERRED;  

ALTER TABLE M_Product ADD CONSTRAINT MProductClass_MProduct FOREIGN KEY (M_Product_Class_ID) REFERENCES M_Product_Class DEFERRABLE INITIALLY DEFERRED; 

ALTER TABLE M_Product ADD CONSTRAINT MProductClassification_MProduc FOREIGN KEY (M_Product_Classification_ID) REFERENCES M_Product_Classification DEFERRABLE INITIALLY DEFERRED;  

ALTER TABLE M_Product ADD CONSTRAINT MProductGroup_MProduct FOREIGN KEY (M_Product_Group_ID) REFERENCES M_Product_Group DEFERRABLE INITIALLY DEFERRED; 

ALTER TABLE M_Product_Class ADD CONSTRAINT MProductClassParent_MProductCl FOREIGN KEY (M_Product_Class_Parent_ID) REFERENCES M_Product_Class DEFERRABLE INITIALLY DEFERRED;  

ALTER TABLE M_Product_Classification ADD CONSTRAINT MClassificationParent_MProduct FOREIGN KEY (M_Classification_Parent_ID) REFERENCES M_Product_Classification DEFERRABLE INITIALLY DEFERRED;  

ALTER TABLE M_Product_Group ADD CONSTRAINT MProductGroupParent_MProductGr FOREIGN KEY (M_Product_Group_Parent_ID) REFERENCES M_Product_Group DEFERRABLE INITIALLY DEFERRED;  

ALTER TABLE M_Production ADD CONSTRAINT COrderLine_MProduction FOREIGN KEY (C_OrderLine_ID) REFERENCES C_OrderLine DEFERRABLE INITIALLY DEFERRED; 

ALTER TABLE M_Production ADD CONSTRAINT MProduct_MProduction FOREIGN KEY (M_Product_ID) REFERENCES M_Product DEFERRABLE INITIALLY DEFERRED;  

ALTER TABLE M_ProductionLine ADD CONSTRAINT MProduction_MProductionLine FOREIGN KEY (M_Production_ID) REFERENCES M_Production DEFERRABLE INITIALLY DEFERRED; 

ALTER TABLE M_Product_QualityTest ADD CONSTRAINT MProduct_MProductQualityTest FOREIGN KEY (M_Product_ID) REFERENCES M_Product DEFERRABLE INITIALLY DEFERRED; 

ALTER TABLE M_Product_QualityTest ADD CONSTRAINT MQualityTest_MProductQualityTe FOREIGN KEY (M_QualityTest_ID) REFERENCES M_QualityTest DEFERRABLE INITIALLY DEFERRED;  

ALTER TABLE M_QualityTestResult ADD CONSTRAINT MQualityTest_MQualityTestResul FOREIGN KEY (M_QualityTest_ID) REFERENCES M_QualityTest DEFERRABLE INITIALLY DEFERRED; 

ALTER TABLE PA_DashboardContent ADD CONSTRAINT ADBrowse_PADashboardContent FOREIGN KEY (AD_Browse_ID) REFERENCES AD_Browse DEFERRABLE INITIALLY DEFERRED; 

ALTER TABLE PA_DashboardContent ADD CONSTRAINT ZoomField_PADashboardContent FOREIGN KEY (Zoom_Field_ID) REFERENCES AD_Browse_Field DEFERRABLE INITIALLY DEFERRED; 

ALTER TABLE PA_DashboardContent ADD CONSTRAINT ZoomTab_PADashboardContent FOREIGN KEY (Zoom_Tab_ID) REFERENCES AD_Tab DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE PA_DashboardContent ADD CONSTRAINT ZoomWindow_PADashboardContent FOREIGN KEY (Zoom_Window_ID) REFERENCES AD_Window DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE PP_MRP ADD CONSTRAINT CProject_PPMRP FOREIGN KEY (C_Project_ID) REFERENCES C_Project DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE PP_MRP ADD CONSTRAINT CProjectPhase_PPMRP FOREIGN KEY (C_ProjectPhase_ID) REFERENCES C_ProjectPhase DEFERRABLE INITIALLY DEFERRED; 

ALTER TABLE PP_MRP ADD CONSTRAINT CProjectTask_PPMRP FOREIGN KEY (C_ProjectTask_ID) REFERENCES C_ProjectTask DEFERRABLE INITIALLY DEFERRED;  

ALTER TABLE PP_MRP_Detail ADD CONSTRAINT MRPDemand_PPMRPDetail FOREIGN KEY (MRP_Demand_ID) REFERENCES PP_MRP DEFERRABLE INITIALLY DEFERRED; 

ALTER TABLE PP_MRP_Detail ADD CONSTRAINT MRPSupply_PPMRPDetail FOREIGN KEY (MRP_Supply_ID) REFERENCES PP_MRP DEFERRABLE INITIALLY DEFERRED; 

ALTER TABLE PP_Order ADD CONSTRAINT CProjectPhase_PPOrder FOREIGN KEY (C_ProjectPhase_ID) REFERENCES C_ProjectPhase DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE PP_Order ADD CONSTRAINT CProjectTask_PPOrder FOREIGN KEY (C_ProjectTask_ID) REFERENCES C_ProjectTask DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE WM_Area ADD CONSTRAINT MWarehouse_WMArea FOREIGN KEY (M_Warehouse_ID) REFERENCES M_Warehouse DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE WM_Area ADD CONSTRAINT WMAreaType_WMArea FOREIGN KEY (WM_Area_Type_ID) REFERENCES WM_Area_Type DEFERRABLE INITIALLY DEFERRED; 

ALTER TABLE WM_Definition ADD CONSTRAINT CBPartner_WMDefinition FOREIGN KEY (C_BPartner_ID) REFERENCES C_BPartner DEFERRABLE INITIALLY DEFERRED;  

ALTER TABLE WM_Definition ADD CONSTRAINT CBPGroup_WMDefinition FOREIGN KEY (C_BP_Group_ID) REFERENCES C_BP_Group DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE WM_Definition ADD CONSTRAINT MProduct_WMDefinition FOREIGN KEY (M_Product_ID) REFERENCES M_Product DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE WM_Definition ADD CONSTRAINT MProductCategory_WMDefinition FOREIGN KEY (M_Product_Category_ID) REFERENCES M_Product_Category DEFERRABLE INITIALLY DEFERRED; 

ALTER TABLE WM_Definition ADD CONSTRAINT WMAreaType_WMDefinition FOREIGN KEY (WM_Area_Type_ID) REFERENCES WM_Area_Type DEFERRABLE INITIALLY DEFERRED;  

ALTER TABLE WM_Definition ADD CONSTRAINT WMSectionType_WMDefinition FOREIGN KEY (WM_Section_Type_ID) REFERENCES WM_Section_Type DEFERRABLE INITIALLY DEFERRED; 

ALTER TABLE WM_Definition ADD CONSTRAINT WMStrategy_WMDefinition FOREIGN KEY (WM_Strategy_ID) REFERENCES WM_Strategy DEFERRABLE INITIALLY DEFERRED; 

ALTER TABLE WM_InOutBound ADD CONSTRAINT ADOrgTrx_WMInOutBound FOREIGN KEY (AD_OrgTrx_ID) REFERENCES AD_Org DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE WM_InOutBound ADD CONSTRAINT DropShipUser_WMInOutBound FOREIGN KEY (DropShip_User_ID) REFERENCES AD_User DEFERRABLE INITIALLY DEFERRED; 

ALTER TABLE WM_InOutBound ADD CONSTRAINT SalesRep_WMInOutBound FOREIGN KEY (SalesRep_ID) REFERENCES AD_User DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE WM_InOutBound ADD CONSTRAINT CActivity_WMInOutBound FOREIGN KEY (C_Activity_ID) REFERENCES C_Activity DEFERRABLE INITIALLY DEFERRED;  

ALTER TABLE WM_InOutBound ADD CONSTRAINT DropShipBPartner_WMInOutBound FOREIGN KEY (DropShip_BPartner_ID) REFERENCES C_BPartner DEFERRABLE INITIALLY DEFERRED; 

ALTER TABLE WM_InOutBound ADD CONSTRAINT DropShipLocation_WMInOutBound FOREIGN KEY (DropShip_Location_ID) REFERENCES C_BPartner_Location DEFERRABLE INITIALLY DEFERRED; 

ALTER TABLE WM_InOutBound ADD CONSTRAINT CCampaign_WMInOutBound FOREIGN KEY (C_Campaign_ID) REFERENCES C_Campaign DEFERRABLE INITIALLY DEFERRED;  

ALTER TABLE WM_InOutBound ADD CONSTRAINT CDocType_WMInOutBound FOREIGN KEY (C_DocType_ID) REFERENCES C_DocType DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE WM_InOutBound ADD CONSTRAINT User1_WMInOutBound FOREIGN KEY (User1_ID) REFERENCES C_ElementValue DEFERRABLE INITIALLY DEFERRED;  

ALTER TABLE WM_InOutBound ADD CONSTRAINT User2_WMInOutBound FOREIGN KEY (User2_ID) REFERENCES C_ElementValue DEFERRABLE INITIALLY DEFERRED;  

ALTER TABLE WM_InOutBound ADD CONSTRAINT MShipper_WMInOutBound FOREIGN KEY (M_Shipper_ID) REFERENCES M_Shipper DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE WM_InOutBound ADD CONSTRAINT MWarehouse_WMInOutBound FOREIGN KEY (M_Warehouse_ID) REFERENCES M_Warehouse DEFERRABLE INITIALLY DEFERRED; 

ALTER TABLE WM_InOutBoundLine ADD CONSTRAINT ADOrgTrx_WMInOutBoundLine FOREIGN KEY (AD_OrgTrx_ID) REFERENCES AD_Org DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE WM_InOutBoundLine ADD CONSTRAINT CActivity_WMInOutBoundLine FOREIGN KEY (C_Activity_ID) REFERENCES C_Activity DEFERRABLE INITIALLY DEFERRED;  

ALTER TABLE WM_InOutBoundLine ADD CONSTRAINT CCampaign_WMInOutBoundLine FOREIGN KEY (C_Campaign_ID) REFERENCES C_Campaign DEFERRABLE INITIALLY DEFERRED;  

ALTER TABLE WM_InOutBoundLine ADD CONSTRAINT CCharge_WMInOutBoundLine FOREIGN KEY (C_Charge_ID) REFERENCES C_Charge DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE WM_InOutBoundLine ADD CONSTRAINT User1_WMInOutBoundLine FOREIGN KEY (User1_ID) REFERENCES C_ElementValue DEFERRABLE INITIALLY DEFERRED; 

ALTER TABLE WM_InOutBoundLine ADD CONSTRAINT User2_WMInOutBoundLine FOREIGN KEY (User2_ID) REFERENCES C_ElementValue DEFERRABLE INITIALLY DEFERRED; 

ALTER TABLE WM_InOutBoundLine ADD CONSTRAINT COrderLine_WMInOutBoundLine FOREIGN KEY (C_OrderLine_ID) REFERENCES C_OrderLine DEFERRABLE INITIALLY DEFERRED;  

ALTER TABLE WM_InOutBoundLine ADD CONSTRAINT CProject_WMInOutBoundLine FOREIGN KEY (C_Project_ID) REFERENCES C_Project DEFERRABLE INITIALLY DEFERRED;  

ALTER TABLE WM_InOutBoundLine ADD CONSTRAINT CProjectPhase_WMInOutBoundLine FOREIGN KEY (C_ProjectPhase_ID) REFERENCES C_ProjectPhase DEFERRABLE INITIALLY DEFERRED; 

ALTER TABLE WM_InOutBoundLine ADD CONSTRAINT CProjectTask_WMInOutBoundLine FOREIGN KEY (C_ProjectTask_ID) REFERENCES C_ProjectTask DEFERRABLE INITIALLY DEFERRED; 

ALTER TABLE WM_InOutBoundLine ADD CONSTRAINT CUOM_WMInOutBoundLine FOREIGN KEY (C_UOM_ID) REFERENCES C_UOM DEFERRABLE INITIALLY DEFERRED; 

ALTER TABLE WM_InOutBoundLine ADD CONSTRAINT MProduct_WMInOutBoundLine FOREIGN KEY (M_Product_ID) REFERENCES M_Product DEFERRABLE INITIALLY DEFERRED;  

ALTER TABLE WM_InOutBoundLine ADD CONSTRAINT WMInOutBound_WMInOutBoundLine FOREIGN KEY (WM_InOutBound_ID) REFERENCES WM_InOutBound DEFERRABLE INITIALLY DEFERRED; 

ALTER TABLE WM_Rule ADD CONSTRAINT ADRule_WMRule FOREIGN KEY (AD_Rule_ID) REFERENCES AD_Rule DEFERRABLE INITIALLY DEFERRED; 

ALTER TABLE WM_Section ADD CONSTRAINT WMArea_WMSection FOREIGN KEY (WM_Area_ID) REFERENCES WM_Area DEFERRABLE INITIALLY DEFERRED; 

ALTER TABLE WM_Section ADD CONSTRAINT WMSectionType_WMSection FOREIGN KEY (WM_Section_Type_ID) REFERENCES WM_Section_Type DEFERRABLE INITIALLY DEFERRED;  

ALTER TABLE WM_Section_Detail ADD CONSTRAINT WMSection_WMSectionDetail FOREIGN KEY (WM_Section_ID) REFERENCES WM_Section DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE WM_Strategy ADD CONSTRAINT MWarehouse_WMStrategy FOREIGN KEY (M_Warehouse_ID) REFERENCES M_Warehouse DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE WM_Strategy_Detail ADD CONSTRAINT WMRule_WMStrategyDetail FOREIGN KEY (WM_Rule_ID) REFERENCES WM_Rule DEFERRABLE INITIALLY DEFERRED;  

ALTER TABLE WM_Strategy_Detail ADD CONSTRAINT WMStrategy_WMStrategyDetail FOREIGN KEY (WM_Strategy_ID) REFERENCES WM_Strategy DEFERRABLE INITIALLY DEFERRED;