alter table AD_VIEW_TRL add constraint AD_VIEW_TRL_KEY primary key("AD_VIEW_ID","AD_LANGUAGE");
alter table AD_VIEW_COLUMN_TRL add constraint AD_VIEW_COLUMN_TRL_KEY primary key("AD_VIEW_COLUMN_ID","AD_LANGUAGE");

alter table AD_BROWSE_TRL add constraint AD_BROWSE_TRL_KEY primary key("AD_BROWSE_ID","AD_LANGUAGE");
ALTER TABLE ad_browse_field_trl DROP CONSTRAINT ad_browse_field_trl_key;
alter table AD_BROWSE_FIELD_TRL add constraint AD_BROWSE_FIELD_TRL_KEY primary key("AD_BROWSE_FIELD_ID","AD_LANGUAGE");
alter table AD_BROWSE_ACCESS add constraint AD_BROWSE_ACCESS_KEY primary key("AD_BROWSE_ID","AD_ROLE_ID");

ALTER TABLE AD_Element ADD (CONSTRAINT ADReference_ADElement FOREIGN KEY (AD_Reference_ID) REFERENCES AD_Reference);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
ALTER TABLE AD_Element ADD (CONSTRAINT ADReferenceValue_ADElement FOREIGN KEY (AD_Reference_Value_ID) REFERENCES AD_Reference);  

ALTER TABLE AD_Browse ADD (CONSTRAINT EntityT_ADBrowse FOREIGN KEY (EntityType) REFERENCES AD_EntityType);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
ALTER TABLE AD_Browse ADD (CONSTRAINT ADProcess_ADBrowse FOREIGN KEY (AD_Process_ID) REFERENCES AD_Process);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
ALTER TABLE AD_Browse ADD (CONSTRAINT ADView_ADBrowse FOREIGN KEY (AD_View_ID) REFERENCES AD_View);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
ALTER TABLE AD_Browse_Access ADD (CONSTRAINT ADBrowse_ADBrowseAccess FOREIGN KEY (AD_Browse_ID) REFERENCES AD_Browse);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
ALTER TABLE AD_Browse_Access ADD (CONSTRAINT ADRole_ADBrowseAccess FOREIGN KEY (AD_Role_ID) REFERENCES AD_Role);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
ALTER TABLE AD_Browse_Field ADD (CONSTRAINT ADBrowse_ADBrowseField FOREIGN KEY (AD_Browse_ID) REFERENCES AD_Browse);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
ALTER TABLE AD_Browse_Field ADD (CONSTRAINT ADElement_ADBrowseField FOREIGN KEY (AD_Element_ID) REFERENCES AD_Element);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
ALTER TABLE AD_Browse_Field ADD (CONSTRAINT EntityT_ADBrowseField FOREIGN KEY (EntityType) REFERENCES AD_EntityType);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
ALTER TABLE AD_Browse_Field ADD (CONSTRAINT ADReference_ADBrowseField FOREIGN KEY (AD_Reference_ID) REFERENCES AD_Reference);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
ALTER TABLE AD_Browse_Field ADD (CONSTRAINT ADReferenceValue_ADBrowseField FOREIGN KEY (AD_Reference_Value_ID) REFERENCES AD_Reference);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
ALTER TABLE AD_Browse_Field ADD (CONSTRAINT ADViewColumn_ADBrowseField FOREIGN KEY (AD_View_Column_ID) REFERENCES AD_View_Column);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
ALTER TABLE AD_Browse_Field ADD (CONSTRAINT AxisColumn_ADBrowseField FOREIGN KEY (Axis_Column_ID) REFERENCES AD_View_Column);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
ALTER TABLE AD_Browse_Field ADD (CONSTRAINT AxisParentColumn_ADBrowseField FOREIGN KEY (Axis_Parent_Column_ID) REFERENCES AD_View_Column);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
ALTER TABLE AD_Browse_Field_Trl ADD (CONSTRAINT ADBrowseField_ADBrowseFieldTrl FOREIGN KEY (AD_Browse_Field_ID) REFERENCES AD_Browse_Field);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
ALTER TABLE AD_Browse_Field_Trl ADD (CONSTRAINT ADLangu_ADBrowseFieldTrl FOREIGN KEY (AD_Language) REFERENCES AD_Language);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
ALTER TABLE AD_Browse_Trl ADD (CONSTRAINT ADLangu_ADBrowseTrl FOREIGN KEY (AD_Language) REFERENCES AD_Language);
ALTER TABLE AD_Browse_Trl ADD (CONSTRAINT ADBrowse_ADBrowseTrl FOREIGN KEY (AD_Browse_ID) REFERENCES AD_Browse);  
ALTER TABLE AD_Menu ADD (CONSTRAINT ADBrowse_ADMenu FOREIGN KEY (AD_Browse_ID) REFERENCES AD_Browse);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
ALTER TABLE AD_Package_Exp_Detail ADD (CONSTRAINT ADBrowse_ADPackageExpDetail FOREIGN KEY (AD_Browse_ID) REFERENCES AD_Browse);
ALTER TABLE AD_Package_Exp_Detail ADD (CONSTRAINT ADPackageExp_ADPackageExpDetai FOREIGN KEY (AD_Package_Exp_ID) REFERENCES AD_Package_Exp);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
ALTER TABLE AD_Package_Exp_Detail ADD (CONSTRAINT ADView_ADPackageExpDetail FOREIGN KEY (AD_View_ID) REFERENCES AD_View);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
ALTER TABLE AD_Process ADD (CONSTRAINT ADBrowse_ADProcess FOREIGN KEY (AD_Browse_ID) REFERENCES AD_Browse);
ALTER TABLE AD_View ADD (CONSTRAINT EntityT_ADView FOREIGN KEY (EntityType) REFERENCES AD_EntityType);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
ALTER TABLE AD_View_Column ADD (CONSTRAINT ADColumn_ADViewColumn FOREIGN KEY (AD_Column_ID) REFERENCES AD_Column);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
ALTER TABLE AD_View_Column ADD (CONSTRAINT EntityT_ADViewColumn FOREIGN KEY (EntityType) REFERENCES AD_EntityType);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
ALTER TABLE AD_View_Column ADD (CONSTRAINT ADView_ADViewColumn FOREIGN KEY (AD_View_ID) REFERENCES AD_View);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
ALTER TABLE AD_View_Column ADD (CONSTRAINT ADViewDefinition_ADViewColumn FOREIGN KEY (AD_View_Definition_ID) REFERENCES AD_View_Definition);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
ALTER TABLE AD_View_Column_Trl ADD (CONSTRAINT ADLangu_ADViewColumnTrl FOREIGN KEY (AD_Language) REFERENCES AD_Language);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
ALTER TABLE AD_View_Column_Trl ADD (CONSTRAINT ADViewColumn_ADViewColumnTrl FOREIGN KEY (AD_View_Column_ID) REFERENCES AD_View_Column);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
ALTER TABLE AD_View_Definition ADD (CONSTRAINT ADTable_ADViewDefinition FOREIGN KEY (AD_Table_ID) REFERENCES AD_Table);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
ALTER TABLE AD_View_Definition ADD (CONSTRAINT ADView_ADViewDefinition FOREIGN KEY (AD_View_ID) REFERENCES AD_View);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
ALTER TABLE AD_View_Trl ADD (CONSTRAINT ADLangu_ADViewTrl FOREIGN KEY (AD_Language) REFERENCES AD_Language);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
ALTER TABLE AD_View_Trl ADD (CONSTRAINT ADView_ADViewTrl FOREIGN KEY (AD_View_ID) REFERENCES AD_View);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
ALTER TABLE AD_WF_Node ADD (CONSTRAINT ADBrowse_ADWFNode FOREIGN KEY (AD_Browse_ID) REFERENCES AD_Browse);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
ALTER TABLE AD_WF_Node ADD (CONSTRAINT ADView_ADWFNode FOREIGN KEY (AD_View_ID) REFERENCES AD_View);     

--DELETE FROM T_Selection_Browse;
--DROP TABLE t_selection_browse;
CREATE TABLE t_selection_browse
(
  ad_pinstance_id NUMBER NOT NULL ENABLE,
  t_selection_id NUMBER NOT NULL ENABLE,
  columnname NVARCHAR2(255) ,
  value_string  NVARCHAR2(255),
  value_date DATE,
  value_number NUMBER,
  info NVARCHAR2(60)
);

ALTER TABLE t_selection_browse ADD CONSTRAINT t_selection_browse_key PRIMARY KEY (ad_pinstance_id, t_selection_id, columnname);
