-- Apr 15, 2013 5:38:37 PM CDT
-- ADEMPIERE-98-Forecast-Management
INSERT INTO AD_Column (AD_Client_ID,AD_Column_ID,AD_Element_ID,AD_Org_ID,AD_Reference_ID,AD_Table_ID,ColumnName,Created,CreatedBy,Description,EntityType,FieldLength,Help,IsActive,IsAllowLogging,IsAlwaysUpdateable,IsAutocomplete,IsEncrypted,IsIdentifier,IsKey,IsMandatory,IsParent,IsSelectionColumn,IsSyncDatabase,IsTranslated,IsUpdateable,Name,SeqNo,Updated,UpdatedBy,Version) VALUES (0,64881,290,0,10,53390,'DocumentNo',TO_DATE('2013-04-15 17:38:36','YYYY-MM-DD HH24:MI:SS'),100,'Document sequence number of the document','EE01',30,'The document number is usually automatically generated by the system and determined by the document type of the document. If the document is not saved, the preliminary number is displayed in "<>".

If the document type of your document has no automatic document sequence defined, the field is empty if you create a new document. This is for documents which usually have an external number (like vendor invoice).  If you leave the field empty, the system will generate a document number for you. The document sequence used for this fallback number is defined in the "Maintain Sequence" window with the name "DocumentNo_<TableName>", where TableName is the actual name of the table (e.g. C_Order).','Y','Y','N','N','N','N','N','N','N','Y','N','N','Y','Document No',0,TO_DATE('2013-04-15 17:38:36','YYYY-MM-DD HH24:MI:SS'),100,0)
;

-- Apr 15, 2013 5:38:37 PM CDT
-- ADEMPIERE-98-Forecast-Management
INSERT INTO AD_Column_Trl (AD_Language,AD_Column_ID, Name, IsTranslated,AD_Client_ID,AD_Org_ID,Created,Createdby,Updated,UpdatedBy) SELECT l.AD_Language,t.AD_Column_ID, t.Name, 'N',t.AD_Client_ID,t.AD_Org_ID,t.Created,t.Createdby,t.Updated,t.UpdatedBy FROM AD_Language l, AD_Column t WHERE l.IsActive='Y' AND l.IsSystemLanguage='Y' AND l.IsBaseLanguage='N' AND t.AD_Column_ID=64881 AND NOT EXISTS (SELECT * FROM AD_Column_Trl tt WHERE tt.AD_Language=l.AD_Language AND tt.AD_Column_ID=t.AD_Column_ID)
;

-- Apr 15, 2013 5:38:41 PM CDT
-- ADEMPIERE-98-Forecast-Management
ALTER TABLE C_SalesHistory ADD DocumentNo NVARCHAR2(30) DEFAULT NULL 
;

-- Apr 15, 2013 5:39:11 PM CDT
-- ADEMPIERE-98-Forecast-Management
INSERT INTO AD_Column (AD_Client_ID,AD_Column_ID,AD_Element_ID,AD_Org_ID,AD_Reference_ID,AD_Table_ID,ColumnName,Created,CreatedBy,Description,EntityType,FieldLength,Help,IsActive,IsAllowLogging,IsAlwaysUpdateable,IsAutocomplete,IsEncrypted,IsIdentifier,IsKey,IsMandatory,IsParent,IsSelectionColumn,IsSyncDatabase,IsTranslated,IsUpdateable,Name,SeqNo,Updated,UpdatedBy,Version) VALUES (0,64882,290,0,10,53386,'DocumentNo',TO_DATE('2013-04-15 17:39:10','YYYY-MM-DD HH24:MI:SS'),100,'Document sequence number of the document','EE01',30,'The document number is usually automatically generated by the system and determined by the document type of the document. If the document is not saved, the preliminary number is displayed in "<>".

If the document type of your document has no automatic document sequence defined, the field is empty if you create a new document. This is for documents which usually have an external number (like vendor invoice).  If you leave the field empty, the system will generate a document number for you. The document sequence used for this fallback number is defined in the "Maintain Sequence" window with the name "DocumentNo_<TableName>", where TableName is the actual name of the table (e.g. C_Order).','Y','Y','N','N','N','N','N','N','N','Y','N','N','Y','Document No',0,TO_DATE('2013-04-15 17:39:10','YYYY-MM-DD HH24:MI:SS'),100,0)
;

-- Apr 15, 2013 5:39:11 PM CDT
-- ADEMPIERE-98-Forecast-Management
INSERT INTO AD_Column_Trl (AD_Language,AD_Column_ID, Name, IsTranslated,AD_Client_ID,AD_Org_ID,Created,Createdby,Updated,UpdatedBy) SELECT l.AD_Language,t.AD_Column_ID, t.Name, 'N',t.AD_Client_ID,t.AD_Org_ID,t.Created,t.Createdby,t.Updated,t.UpdatedBy FROM AD_Language l, AD_Column t WHERE l.IsActive='Y' AND l.IsSystemLanguage='Y' AND l.IsBaseLanguage='N' AND t.AD_Column_ID=64882 AND NOT EXISTS (SELECT * FROM AD_Column_Trl tt WHERE tt.AD_Language=l.AD_Language AND tt.AD_Column_ID=t.AD_Column_ID)
;

-- Apr 15, 2013 5:39:15 PM CDT
-- ADEMPIERE-98-Forecast-Management
ALTER TABLE I_SalesHistory ADD DocumentNo NVARCHAR2(30) DEFAULT NULL 
;

-- Apr 15, 2013 5:39:38 PM CDT
-- ADEMPIERE-98-Forecast-Management
INSERT INTO AD_Field (AD_Client_ID,AD_Column_ID,AD_Field_ID,AD_Org_ID,AD_Tab_ID,Created,CreatedBy,Description,DisplayLength,EntityType,Help,IsActive,IsCentrallyMaintained,IsDisplayed,IsEncrypted,IsFieldOnly,IsHeading,IsReadOnly,IsSameLine,Name,Updated,UpdatedBy) VALUES (0,64882,66132,0,53516,TO_DATE('2013-04-15 17:39:38','YYYY-MM-DD HH24:MI:SS'),100,'Document sequence number of the document',30,'EE01','The document number is usually automatically generated by the system and determined by the document type of the document. If the document is not saved, the preliminary number is displayed in "<>".

If the document type of your document has no automatic document sequence defined, the field is empty if you create a new document. This is for documents which usually have an external number (like vendor invoice).  If you leave the field empty, the system will generate a document number for you. The document sequence used for this fallback number is defined in the "Maintain Sequence" window with the name "DocumentNo_<TableName>", where TableName is the actual name of the table (e.g. C_Order).','Y','Y','Y','N','N','N','N','N','Document No',TO_DATE('2013-04-15 17:39:38','YYYY-MM-DD HH24:MI:SS'),100)
;

-- Apr 15, 2013 5:39:38 PM CDT
-- ADEMPIERE-98-Forecast-Management
INSERT INTO AD_Field_Trl (AD_Language,AD_Field_ID, Description,Help,Name, IsTranslated,AD_Client_ID,AD_Org_ID,Created,Createdby,Updated,UpdatedBy) SELECT l.AD_Language,t.AD_Field_ID, t.Description,t.Help,t.Name, 'N',t.AD_Client_ID,t.AD_Org_ID,t.Created,t.Createdby,t.Updated,t.UpdatedBy FROM AD_Language l, AD_Field t WHERE l.IsActive='Y' AND l.IsSystemLanguage='Y' AND l.IsBaseLanguage='N' AND t.AD_Field_ID=66132 AND NOT EXISTS (SELECT * FROM AD_Field_Trl tt WHERE tt.AD_Language=l.AD_Language AND tt.AD_Field_ID=t.AD_Field_ID)
;

-- Apr 15, 2013 5:40:32 PM CDT
-- ADEMPIERE-98-Forecast-Management
UPDATE AD_Field SET SeqNo=270,IsDisplayed='Y' WHERE AD_Field_ID=66132
;

-- Apr 15, 2013 5:40:32 PM CDT
-- ADEMPIERE-98-Forecast-Management
UPDATE AD_Field SET SeqNo=280,IsDisplayed='Y' WHERE AD_Field_ID=64422
;

-- Apr 15, 2013 5:40:32 PM CDT
-- ADEMPIERE-98-Forecast-Management
UPDATE AD_Field SET SeqNo=290,IsDisplayed='Y' WHERE AD_Field_ID=64423
;

-- Apr 15, 2013 5:40:32 PM CDT
-- ADEMPIERE-98-Forecast-Management
UPDATE AD_Field SET SeqNo=300,IsDisplayed='Y' WHERE AD_Field_ID=64424
;

-- Apr 15, 2013 5:40:32 PM CDT
-- ADEMPIERE-98-Forecast-Management
UPDATE AD_Field SET SeqNo=310,IsDisplayed='Y' WHERE AD_Field_ID=64425
;

-- Apr 15, 2013 5:40:32 PM CDT
-- ADEMPIERE-98-Forecast-Management
UPDATE AD_Field SET SeqNo=320,IsDisplayed='Y' WHERE AD_Field_ID=64426
;

-- Apr 15, 2013 5:40:32 PM CDT
-- ADEMPIERE-98-Forecast-Management
UPDATE AD_Field SET SeqNo=330,IsDisplayed='Y' WHERE AD_Field_ID=64427
;

-- Apr 15, 2013 5:40:32 PM CDT
-- ADEMPIERE-98-Forecast-Management
UPDATE AD_Field SET SeqNo=340,IsDisplayed='Y' WHERE AD_Field_ID=64428
;

-- Apr 15, 2013 5:40:32 PM CDT
-- ADEMPIERE-98-Forecast-Management
UPDATE AD_Field SET SeqNo=350,IsDisplayed='Y' WHERE AD_Field_ID=64429
;

-- Apr 15, 2013 5:40:32 PM CDT
-- ADEMPIERE-98-Forecast-Management
UPDATE AD_Field SET SeqNo=360,IsDisplayed='Y' WHERE AD_Field_ID=64430
;

-- Apr 15, 2013 5:40:32 PM CDT
-- ADEMPIERE-98-Forecast-Management
UPDATE AD_Field SET SeqNo=370,IsDisplayed='Y' WHERE AD_Field_ID=64431
;

-- Apr 15, 2013 5:40:32 PM CDT
-- ADEMPIERE-98-Forecast-Management
UPDATE AD_Field SET SeqNo=380,IsDisplayed='Y' WHERE AD_Field_ID=64432
;

-- Apr 15, 2013 5:40:32 PM CDT
-- ADEMPIERE-98-Forecast-Management
UPDATE AD_Field SET SeqNo=390,IsDisplayed='Y' WHERE AD_Field_ID=64433
;

-- Apr 15, 2013 5:40:32 PM CDT
-- ADEMPIERE-98-Forecast-Management
UPDATE AD_Field SET SeqNo=400,IsDisplayed='Y' WHERE AD_Field_ID=64434
;

-- Apr 15, 2013 5:40:32 PM CDT
-- ADEMPIERE-98-Forecast-Management
UPDATE AD_Field SET SeqNo=410,IsDisplayed='Y' WHERE AD_Field_ID=64435
;

-- Apr 15, 2013 5:40:32 PM CDT
-- ADEMPIERE-98-Forecast-Management
UPDATE AD_Field SET SeqNo=420,IsDisplayed='Y' WHERE AD_Field_ID=64436
;

-- Apr 15, 2013 5:40:32 PM CDT
-- ADEMPIERE-98-Forecast-Management
UPDATE AD_Field SET SeqNo=430,IsDisplayed='Y' WHERE AD_Field_ID=64437
;

-- Apr 15, 2013 5:40:32 PM CDT
-- ADEMPIERE-98-Forecast-Management
UPDATE AD_Field SET SeqNo=440,IsDisplayed='Y' WHERE AD_Field_ID=64438
;

-- Apr 15, 2013 5:40:32 PM CDT
-- ADEMPIERE-98-Forecast-Management
UPDATE AD_Field SET SeqNo=450,IsDisplayed='Y' WHERE AD_Field_ID=64439
;

-- Apr 15, 2013 5:42:13 PM CDT
-- ADEMPIERE-98-Forecast-Management
UPDATE AD_Field SET SeqNo=270,IsDisplayed='Y' WHERE AD_Field_ID=64422
;

-- Apr 15, 2013 5:42:13 PM CDT
-- ADEMPIERE-98-Forecast-Management
UPDATE AD_Field SET SeqNo=280,IsDisplayed='Y' WHERE AD_Field_ID=64423
;

-- Apr 15, 2013 5:42:13 PM CDT
-- ADEMPIERE-98-Forecast-Management
UPDATE AD_Field SET SeqNo=290,IsDisplayed='Y' WHERE AD_Field_ID=64424
;

-- Apr 15, 2013 5:42:13 PM CDT
-- ADEMPIERE-98-Forecast-Management
UPDATE AD_Field SET SeqNo=300,IsDisplayed='Y' WHERE AD_Field_ID=64425
;

-- Apr 15, 2013 5:42:13 PM CDT
-- ADEMPIERE-98-Forecast-Management
UPDATE AD_Field SET SeqNo=310,IsDisplayed='Y' WHERE AD_Field_ID=64426
;

-- Apr 15, 2013 5:42:13 PM CDT
-- ADEMPIERE-98-Forecast-Management
UPDATE AD_Field SET SeqNo=320,IsDisplayed='Y' WHERE AD_Field_ID=66132
;

-- Apr 15, 2013 5:42:34 PM CDT
-- ADEMPIERE-98-Forecast-Management
UPDATE AD_Field SET AD_FieldGroup_ID=104,Updated=TO_DATE('2013-04-15 17:42:34','YYYY-MM-DD HH24:MI:SS'),UpdatedBy=100 WHERE AD_Field_ID=66132
;

-- Apr 15, 2013 5:42:48 PM CDT
-- ADEMPIERE-98-Forecast-Management
INSERT INTO AD_Field (AD_Client_ID,AD_Column_ID,AD_Field_ID,AD_Org_ID,AD_Tab_ID,Created,CreatedBy,Description,DisplayLength,EntityType,Help,IsActive,IsCentrallyMaintained,IsDisplayed,IsEncrypted,IsFieldOnly,IsHeading,IsReadOnly,IsSameLine,Name,Updated,UpdatedBy) VALUES (0,64881,66133,0,53520,TO_DATE('2013-04-15 17:42:47','YYYY-MM-DD HH24:MI:SS'),100,'Document sequence number of the document',30,'EE01','The document number is usually automatically generated by the system and determined by the document type of the document. If the document is not saved, the preliminary number is displayed in "<>".

If the document type of your document has no automatic document sequence defined, the field is empty if you create a new document. This is for documents which usually have an external number (like vendor invoice).  If you leave the field empty, the system will generate a document number for you. The document sequence used for this fallback number is defined in the "Maintain Sequence" window with the name "DocumentNo_<TableName>", where TableName is the actual name of the table (e.g. C_Order).','Y','Y','Y','N','N','N','N','N','Document No',TO_DATE('2013-04-15 17:42:47','YYYY-MM-DD HH24:MI:SS'),100)
;

-- Apr 15, 2013 5:42:48 PM CDT
-- ADEMPIERE-98-Forecast-Management
INSERT INTO AD_Field_Trl (AD_Language,AD_Field_ID, Description,Help,Name, IsTranslated,AD_Client_ID,AD_Org_ID,Created,Createdby,Updated,UpdatedBy) SELECT l.AD_Language,t.AD_Field_ID, t.Description,t.Help,t.Name, 'N',t.AD_Client_ID,t.AD_Org_ID,t.Created,t.Createdby,t.Updated,t.UpdatedBy FROM AD_Language l, AD_Field t WHERE l.IsActive='Y' AND l.IsSystemLanguage='Y' AND l.IsBaseLanguage='N' AND t.AD_Field_ID=66133 AND NOT EXISTS (SELECT * FROM AD_Field_Trl tt WHERE tt.AD_Language=l.AD_Language AND tt.AD_Field_ID=t.AD_Field_ID)
;

-- Apr 15, 2013 5:43:03 PM CDT
-- ADEMPIERE-98-Forecast-Management
UPDATE AD_Field SET SeqNo=210,IsDisplayed='Y' WHERE AD_Field_ID=66133
;

-- Apr 15, 2013 5:43:03 PM CDT
-- ADEMPIERE-98-Forecast-Management
UPDATE AD_Field SET SeqNo=220,IsDisplayed='Y' WHERE AD_Field_ID=64492
;

-- Apr 15, 2013 5:43:03 PM CDT
-- ADEMPIERE-98-Forecast-Management
UPDATE AD_Field SET SeqNo=230,IsDisplayed='Y' WHERE AD_Field_ID=64493
;

-- Apr 15, 2013 5:43:03 PM CDT
-- ADEMPIERE-98-Forecast-Management
UPDATE AD_Field SET SeqNo=240,IsDisplayed='Y' WHERE AD_Field_ID=64494
;

-- Apr 15, 2013 5:43:03 PM CDT
-- ADEMPIERE-98-Forecast-Management
UPDATE AD_Field SET SeqNo=250,IsDisplayed='Y' WHERE AD_Field_ID=64495
;

-- Apr 15, 2013 5:43:03 PM CDT
-- ADEMPIERE-98-Forecast-Management
UPDATE AD_Field SET SeqNo=260,IsDisplayed='Y' WHERE AD_Field_ID=64496
;

-- Apr 15, 2013 5:43:03 PM CDT
-- ADEMPIERE-98-Forecast-Management
UPDATE AD_Field SET SeqNo=270,IsDisplayed='Y' WHERE AD_Field_ID=64497
;

-- Apr 15, 2013 5:43:03 PM CDT
-- ADEMPIERE-98-Forecast-Management
UPDATE AD_Field SET SeqNo=280,IsDisplayed='Y' WHERE AD_Field_ID=64498
;

-- Apr 15, 2013 5:43:03 PM CDT
-- ADEMPIERE-98-Forecast-Management
UPDATE AD_Field SET SeqNo=290,IsDisplayed='Y' WHERE AD_Field_ID=64499
;

-- Apr 15, 2013 5:43:16 PM CDT
-- ADEMPIERE-98-Forecast-Management
UPDATE AD_Field SET AD_FieldGroup_ID=104,Updated=TO_DATE('2013-04-15 17:43:16','YYYY-MM-DD HH24:MI:SS'),UpdatedBy=100 WHERE AD_Field_ID=66133
;

-- Apr 15, 2013 5:44:03 PM CDT
-- ADEMPIERE-98-Forecast-Management
UPDATE AD_Field SET DisplayLength=29,Updated=TO_DATE('2013-04-15 17:44:03','YYYY-MM-DD HH24:MI:SS'),UpdatedBy=100 WHERE AD_Field_ID=66133
;

-- Apr 15, 2013 5:44:29 PM CDT
-- ADEMPIERE-98-Forecast-Management
UPDATE AD_Field SET DisplayLength=29,Updated=TO_DATE('2013-04-15 17:44:29','YYYY-MM-DD HH24:MI:SS'),UpdatedBy=100 WHERE AD_Field_ID=66132
;

