/*
 * Generated by XDoclet - Do not edit!
 */
package org.compiere.interfaces;

/**
 * Local interface for adempiere/Status.
 */
public interface StatusLocal
   extends javax.ejb.EJBLocalObject
{
   /**
    * Get Version (Date)
    * @return version e.g. 2002-09-02    */
   public java.lang.String getDateVersion(  ) ;

   /**
    * Get Main Version
    * @return main version - e.g. Version 2.4.3b    */
   public java.lang.String getMainVersion(  ) ;

   /**
    * Get Database Type
    * @return Database Type    */
   public java.lang.String getDbType(  ) ;

   /**
    * Get Database Host
    * @return Database Host Name    */
   public java.lang.String getDbHost(  ) ;

   /**
    * Get Database Port
    * @return Database Port    */
   public int getDbPort(  ) ;

   /**
    * Get Database SID
    * @return Database SID    */
   public java.lang.String getDbName(  ) ;

   /**
    * Get Database URL
    * @return Database URL    */
   public java.lang.String getConnectionURL(  ) ;

   /**
    * Get Database UID
    * @return Database User Name    */
   public java.lang.String getDbUid(  ) ;

   /**
    * Get Database PWD
    * @return Database User Password    */
   public java.lang.String getDbPwd(  ) ;

   /**
    * Get Connection Manager Host
    * @return Connection Manager Host    */
   public java.lang.String getFwHost(  ) ;

   /**
    * Get Connection Manager Port
    * @return Connection Manager Port    */
   public int getFwPort(  ) ;

   /**
    * Get Version Count
    * @return number of version inquiries    */
   public int getVersionCount(  ) ;

   /**
    * Get Database Count
    * @return number of database inquiries    */
   public int getDatabaseCount(  ) ;

   /**
    * Describes the instance and its content for debugging purpose
    * @return Debugging information about the instance and its content    */
   public java.lang.String getStatus(  ) ;

}
