-- May 7, 2009 1:59:22 AM ECT
-- Advanced Search
CREATE TABLE C_CashFlow (AD_Client_ID NUMBER(10) NOT NULL, AD_OrgTrx_ID NUMBER(10) NOT NULL, AD_Org_ID NUMBER(10) NOT NULL, C_BPartner_ID NUMBER(10) NOT NULL, C_BankAccount_ID NUMBER(10) DEFAULT NULL , C_CashFlow_ID NUMBER(10) DEFAULT NULL , C_ConversionType_ID NUMBER(10) DEFAULT NULL , C_Currency_ID NUMBER(10) NOT NULL, C_PaymentTerm_ID NUMBER(10) NOT NULL, Created DATE NOT NULL, CreatedBy NUMBER(10) NOT NULL, DateInvoiced DATE NOT NULL, Description NVARCHAR2(255) DEFAULT NULL , DocumentNo NVARCHAR2(30) NOT NULL, DueDate DATE DEFAULT NULL , GrandTotal NUMBER DEFAULT NULL , IsActive CHAR(1) DEFAULT NULL  CHECK (IsActive IN ('Y','N')), IsSOTrx CHAR(1) DEFAULT NULL  CHECK (IsSOTrx IN ('Y','N')), Name NVARCHAR2(60) DEFAULT NULL , Updated DATE NOT NULL, UpdatedBy NUMBER(10) NOT NULL, CONSTRAINT C_CashFlow_Key PRIMARY KEY (C_CashFlow_ID))
;

